ARESET
TWOTONE ASPDIR:RTEST 20,500 ASPDIR:BTEST 20,500 TRUE 3 TEST
$ INQ WAITING
ARESET
AFLASH TEST 128 =
APERFOT TEST FOTLOG
ABLOCK = = =
LUTTWEAK
AFLASH ASPDIR:HORSE 384 =
ASAVE TEST
$ INQ WAITING
ARESET
AFLASH TEST = =
AHARDCOPY TEST
$ DEL AHARDCOPY.LIS;*
$ DEL APERFOT.LIS;*
$ DEL TEST.BDF;*

