!
!++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!
!      ***********************
!      *                     *
!      * PROCEDURE BATIMSTAC *
!      *                     *
!      ***********************
!
!
!       CALLING SEQUENCE
!             BATIMSTAC
!
!
!       FUNCTION:-
!           Runs IMSTACK as a batch job
!           This stacks together images which are linear with intensity
!           have zero intensity at zero and are already closely aligned.
!
!
!
!      A J PENNY                   RGO                       82-NOV
!---------------------------------------------------------------------
!
!
!
!
!  USES
!   This package
!          PSTACK,ASXY
!   EDRS package
!          XYKEY,FFCLEAN,CENTROID,RESAMPLE,ARITH,IMGARITH
!
!  WRITTEN BY:-
!     A.J.Penny                                 82-7-19
! --------------------------------------------------------------
!
!
!
!
INQUIRE P20 "NAME TO BE GIVEN TO FILE EXECUTING BATCH JOB ?"
$ OPEN/WRITE OUTPUT_FILE 'P20'.COM
WRITE OUTPUT_FILE "$ SET NOVERIFY"
!
!
INQUIRE P19 "BATCH OR FASTBATCH (B/F) ?"
!
INQUIRE P21 "NUMBER OF USER DISK WANTED (0 IF NONE) ?"
IF P21 .EQS. "3" THEN WRITE OUTPUT_FILE "$ MOUNT/SHARE DRC2: USER3"
IF P21 .EQS. "4" THEN WRITE OUTPUT_FILE "$ MOUNT/SHARE DRC2: USER4"
!
!
WRITE OUTPUT_FILE "$ DSCL"
WRITE OUTPUT_FILE "IMSTACK"
!
!
!
INQUIRE P1 "STACKING AND OUTPUT TO BE DONE IN DISK ? "
WRITE OUTPUT_FILE P1
!
!
!
WRITE SYS$OUTPUT " "
INQUIRE P2 "IMAGES TO BE FFCLEANED BEFORE STACKING (Y/N) ? "
WRITE OUTPUT_FILE P2
IF P2 .NES. "Y" THEN GOTO K1
INQUIRE P3 "FFCLEAN BOX SIZE (USUALLY 3) ? "
WRITE OUTPUT_FILE P3
K1:
!
!
!
WRITE SYS$OUTPUT " "
INQUIRE P4 "IMAGES TO BE TURNED TO FIT BEFORE STACKING (Y/N) ? "
WRITE OUTPUT_FILE P4
IF P4 .NES. "Y" THEN GOTO J1
WRITE SYS$OUTPUT " "
WRITE SYS$OUTPUT "TURNING TO BE DONE BY COORDINATE FILES MADE FROM"
INQUIRE P5 "FILES (F), OR FIT TO STARS IN IMAGE (C) ?"
WRITE OUTPUT_FILE P5
J1:
!
!
!
WRITE SYS$OUTPUT " "
INQUIRE P6 "OUTPUT TO BE IN FILE NAME (OMIT DISK PREFIX) ? "
WRITE OUTPUT_FILE P6
!
!
!
WRITE SYS$OUTPUT " "
WRITE SYS$OUTPUT "STACKING METHOD TO USE IS"
INQUIRE P7 "MEAN; MODE; MEDIAN; SUM ? "
WRITE OUTPUT_FILE P7
ERRMD := CALC
IF P7 .EQS. "SUM" THEN GOTO L1
WRITE SYS$OUTPUT " "
WRITE SYS$OUTPUT "GET SKY LEVEL AND ERRORS FOR NORMALISING AND"
WRITE SYS$OUTPUT "WEIGHTING BY LETTING CALCS OCCUR, OR FROM KEYBOARD"
INQUIRE P8 "INPUT OF VALUES (CALC/KEY) ? "
WRITE OUTPUT_FILE P8
L1:
IF P7 .EQS. "SUM" THEN GOTO N1
WRITE SYS$OUTPUT " "
WRITE SYS$OUTPUT " AREA TO BE USED TO FIND SKY LEVEL AND NOISE"
INQUIRE P9 "X START OF REFERENCE AREA ? "
WRITE OUTPUT_FILE P9
INQUIRE P10   "X END OF REFERENCE AREA ? "
WRITE OUTPUT_FILE P10
INQUIRE P11 "Y START OF REFERENCE AREA ? "
WRITE OUTPUT_FILE P11
INQUIRE P12   "Y END OF REFERENCE AREA ? "
WRITE OUTPUT_FILE P12
N1:
!
!
!
IF P4 .NES. "Y" THEN GOTO G2
IF P5 .NES. "F" THEN GOTO G2
WRITE SYS$OUTPUT " "
INQUIRE P13 "NAME OF STANDARD COORDINATE FILE IS ?"
WRITE OUTPUT_FILE P13
G2:
IF P4 .NES. "Y" THEN GOTO G3
IF P5 .NES. "C" THEN GOTO G3
WRITE SYS$OUTPUT " "
INQUIRE P13 "NAME OF STANDARD COORDINATE FILE IS ? "
WRITE OUTPUT_FILE P13
INQUIRE P14 "CENTROID BOX SIZE = ? "
WRITE OUTPUT_FILE P14
INQUIRE P15 "CENTROID MAX SHIFT = ? "
WRITE OUTPUT_FILE P15
G3:
!
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!   LOOP GETTING IMAGES      !!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!
!
COUNT=0
!
A1:
!
COUNT=COUNT + 1
!
WRITE SYS$OUTPUT " "
INQUIRE P16 "NAME OF FILE ''COUNT' ? "
WRITE OUTPUT_FILE P16
IF P16 .EQS. "" THEN GOTO A2
!
!
IF P4 .NES. "Y" THEN GOTO H2
IF P5 .NES. "F" THEN GOTO H2
INQUIRE P17 "NAME OF COORDINATE FILE IS ? "
WRITE OUTPUT_FILE P17
H2:
!
IF P7 .EQS. "SUM" THEN GOTO H3
IF P8 .NES. "KEY" THEN GOTO H3
INQUIRE P18 " STD DEV (AFTER NORMALISATION) OF SKY NOISE ? "
WRITE OUTPUT_FILE P18
H3:
!
GOTO A1
!
A2:
!
TOT=COUNT - 1
!
!
!
WRITE OUTPUT_FILE "STOP"
WRITE OUTPUT_FILE "$ EXIT"
$ CLOSE OUTPUT_FILE
$ IF P19 .EQS. "B" THEN SUBMIT 'P20'
$ IF P19 .EQS. "F" THEN SUBMIT/QUEUE=FASTBATCH 'P20'



