!
!++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!
!
!
!
!                    !!!!!!!!!!!!!!!!!!!!!
!                    !                   !
!                    ! BATLORSIM.SCL     !
!                    !                   !
!                    !!!!!!!!!!!!!!!!!!!!!
!
!
!
!   THIS PROCEEDURE MAKES A FILE TO RUN LORSIM AS A BATCH JOB
!
!    THE PROGRAM PROMPTS FOR COMMANDS IN THE SAME MANNER AS "LORSIM"
! AND THEN CREATES A COMMAND FILE WHICH WILL RUN EITHER IN BATCH OR 
! FASTBATCH.
!
!
!
!      T A JONES                                       82-SEP-14
!------------------------------------------------------------------
!
!
!
!
!
!
WRITE SYS$OUTPUT "RUNNING LORSIM AS A BATCH JOB"
WRITE SYS$OUTPUT " "
INQUIRE P1 "IMAGE ?"           ! MUST USE FULL (NOT ABBREVIATED) FILE NAME
INQUIRE P2 "XYLIST ?"
INQUIRE P3 "OUTPUT FILE ?"
INQUIRE P16 "OUTPUT FILE TITLE ?"
INQUIRE P12 "PARFIX ? (YES/NO)"
INQUIRE P4 "RX ?"
INQUIRE P5 "RY ?"
INQUIRE P6 "P ?"
INQUIRE P7 "PRX ?"
INQUIRE P8 "PRY ?"
INQUIRE P13 "VOLCAL ? (YES/NO)"
INQUIRE P14 "XBOX ?"
INQUIRE P15 "YBOX ?"
INQUIRE P9 "BATCH OR FASTBATCH (B/F)"
INQUIRE P10 "NAME TO BE GIVEN TO FILE EXECUTING BATCH JOB"
INQUIRE P11 "IF USING USER3 TYPE 3, IF USER4 TYPE 4, IF NEITHER 0"
!
!
!
OPEN/WRITE OUTPUT_FILE 'P10'.COM
WRITE OUTPUT_FILE "$ SET NOVERIFY"
IF P11 .EQS. "3" THEN WRITE OUTPUT_FILE "$ MOUNT/SHARE DRC2: USER3"
IF P11 .EQS. "4" THEN WRITE OUTPUT_FILE "$ MOUNT/SHARE DRC2: USER4"
WRITE OUTPUT_FILE "$ DSCL"
WRITE OUTPUT_FILE "LORSIM"
WRITE OUTPUT_FILE P1
WRITE OUTPUT_FILE P2
WRITE OUTPUT_FILE P3
WRITE OUTPUT_FILE P16
WRITE OUTPUT_FILE P12
WRITE OUTPUT_FILE P4
WRITE OUTPUT_FILE P5
WRITE OUTPUT_FILE P6
WRITE OUTPUT_FILE P7
WRITE OUTPUT_FILE P8
WRITE OUTPUT_FILE P13
WRITE OUTPUT_FILE P14
WRITE OUTPUT_FILE P15
WRITE OUTPUT_FILE "STOP"
WRITE OUTPUT_FILE "$ EXIT"
CLOSE OUTPUT_FILE
IF P9 .EQS. "B" THEN SUBMIT 'P10'.COM
IF P9 .EQS. "F" THEN SUBMIT/QUEUE=FASTBATCH 'P10'.COM
