!
!+
! PROCEDURE TO DEMOSTRATE A USE OF THE ASPIC ROUTINE AUCUR
!
! THERE MUST BE AN IMAGE ON THE STACK
!
! USE BUTTONS 2 & 3 TO INCREASE/DECREASE THE AREA COVERED BY THE
! USER BOX CURSOR
!
! WHEN BUTTON 1 IS PRESSED THE PROCEDURE WILL ZOOM THE IMAGE AS
! LARGE AS POSSIBLE SO THAT THE AREA DEFINED CAN STILL BE SEEN
!
!

AUCUR = = = = 2
ZOOM= 256/'AUCUR_ARAD1'
EZOOM=('ZOOM'/2)*2
IF EZOOM.GT.16 THEN  EZOOM=16
ZX='AUCUR_AX1'
ZY='AUCUR_AY1'
AZOOM 'ZX' 'ZY' 'EZOOM' 'EZOOM'
