!+	Procedure CLRLIM
!
!	Part of the IAM suite, clears histogram limits in
!	IAMHIS,SETLIM and GETLIM
!
!	D. Tudhope/ROE/Sept 1982
!
!- *

CLEAR IAMHISP_HMIND
CLEAR IAMHISP_HMAXD
CLEAR IAMHISP_HMIN
CLEAR IAMHISP_HMAX
CLEAR SETLIMP_HMIN
CLEAR SETLIMP_HMAX
CLEAR SETLIMP_HMIND
CLEAR SETLIMP_HMAXD
CLEAR GETLIMP_HMIN
CLEAR GETLIMP_HMAX
