!+
!
!     PROCEDURE    *** EDDOC ***
! 
!     THIS PROCEDURE ALLOWS THE USER TO EDIT A .GRF FILE
!     CREATED BY PROCEDURE CREDOC , RUN THE RESULT THROUGH GEROFF
!     AND PRINT THE RESULTS.
!
!     IT HAS A SINGLE OPTIONAL PARAMETER
!
!         P1      THE NAME OF THE PROGRAM (OR WHTEVER)
!                 BEING DOCUMENTED.
!
!      WRITTEN BY K F HARTLEY AT RGO ON 15/12/81
!
!
      IF P1.EQS."" THEN INQUIRE P1 "PROGRAM NAME?"
      EDIT 'P1'.GRF 
      GEROFF 'P1'.GRF 'P1'.DOC
      PRINT/NOFLAG/NOFEED 'P1'.DOC
