$ !+
$ !    ASPIC/DSCL PROCEDURE    *** FCDISP ***
$ ! 
$ !    WRITTEN BY K F HARTLEY AT RGO ON 1/10/81
$ !
$ !    DISPLAYS A FALSE COLOUR IMAGE WITH AN
$ !    APPROPRIATE LOOK-UP-TABLE AND ZOOM
$ !
$ !    REQUIRES 3 PARAMETERS :-
$ !      IMAGE
$ !      X0
$ !      Y0
      ADISP 'P1' 'P2' 'P3' 'P4' TRIM=FALSE
      LUTFC
      AZOOM = = = =
