!+	Procedure GETLIM
!
!	part of IAM suite.
!
!	GETLIMP returning results to IAMHISP and SETLIMP
!	SCLSTAT tells if program terminated successfully
!
!	D. Tudhope/ROE/Sept 1982
!
!- *
LET GETLIMP_SCLSTAT=1
GETLIMP
LET GLOBAL_SCLSTAT=GETLIMP_SCLSTAT   !   cos of bugs in dscl
IF GLOBAL_SCLSTAT.NE.0 THEN GOTO ERROR
LET IAMHISP_HMIN=GETLIMP_HMIN
LET IAMHISP_HMAX=GETLIMP_HMAX
LET SETLIMP_HMIN=GETLIMP_HMIN
LET SETLIMP_HMAX=GETLIMP_HMAX
EXIT
ERROR:
WRITE SYS$OUTPUT "PROGRAM ABORTED - NO ACTION TAKEN"
