!+	Procedure INDPIX
C
C    modifies indicated pixel (CX,CY) to value NEWVAL
C    first copies INPICT to OUTPICT and then modifies OUTPICT
!
!	USES INDPIX WITH CURSOR WITH INPUT FROM AND OUTPUT TO STACK
!
!	D. TUDHOPE/ROE
!
!- *
ARGSCUR
LET DSCL_I=ARGSCUR_IMAGEN
IF DSCL_I.EQ.0 THEN GOTO ERROR                    ! error in cursor, give up
IF P1.NES."" THEN LET INDPIXP_NEWVAL='P1'         ! LEAVE ALONE IF NO ARGUMENT
LET INDPIXP_INPICT=$
LET INDPIXP_OUTPICT=$
LET INDPIXP_CX=ARGSCUR_CX
LET INDPIXP_CY=ARGSCUR_CY
INDPIXP
CLEAR INDPIXP_NEWVAL
EXIT
ERROR:
WRITE SYS$OUTPUT "PROCEDURE ABANDONED"
