!+	Procedure LINFIX
!
!    modifies indicated horizontal line (CY) to value NEWVAL
!    first copies INPICT to OUTPICT and then modifies OUTPICT
!
!	USES LINFIXP WITH CURSOR WITH INPUT FROM AND OUTPUT TO STACK
!	D. TUDHOPE/ROE
!
!- *
ARGSCUR
LET DSCL_I=ARGSCUR_IMAGEN
IF DSCL_I.EQ.0 THEN GOTO ERROR                    ! error in cursor, give up
IF P1.NES."" THEN LET LINFIXP_NEWVAL='P1'         ! LEAVE ALONE IF NO ARGUMENT
LET LINFIXP_INPICT=$
LET LINFIXP_OUTPICT=$
LET LINFIXP_CY=ARGSCUR_CY
LINFIXP
CLEAR LINFIXP_NEWVAL
EXIT
ERROR:
WRITE SYS$OUTPUT "PROCEDURE ABANDONED"
