!+	Procedure LOFREQ
!
!    Eliminates low frequencies from fft mode image which is
!    assumed to have been generated by DFFTASP as here the
!    zero frequency is assumed to lie at IXEXT/2-1,IYEXT/2
!    in args coords 0..511 CIRFIL called to put everything
!    inside circle to 0.
!    Size of circle derived from ARGSCIR
!
!    USES LOFREQP WITH CIRCULAR CURSOR WITH INPUT FROM AND OUTPUT TO STACK
!
!    D. TUDHOPE/ROE
!
!- *
ARGSCIR
LET DSCL_I=ARGSCIR_IMAGEN
IF DSCL_I.EQ.0 THEN GOTO ERROR                    ! error in cursor, give up
LET LOFREQP_INPICT=$
LET LOFREQP_OUTPICT=$
LET LOFREQP_DIAM=ARGSCIR_DIAM
LOFREQP
EXIT
ERROR:
WRITE SYS$OUTPUT "PROCEDURE ABANDONED"
