!+
!      DSCL PROCEDURE - *** LUTFC ***
!
!      WRITTEN BY K F HARTLEY AT RGO ON 2/9/81
!
!      LOADS THE ARGS LOOK-UP-TABLE WITH VALUES SUITABLE FOR
!      DISPLAYING FALSE COLOUR IMAGES.
!      [ IN FACT IT IS THE OLD "KAPE" LUT , NOW RELABLED "FCLUT"
!
     LUTREAD DSCL_BDFDIR:FCLUT
     EXIT
