!+	Procedure OUTSET
!
!    Sets values outside a specified circle to value NEWVAL.
!    First copies INPICT to OUTPICT and then modifies OUTPICT
!
!    USES OUTSETP WITH CIRCULAR CURSOR WITH INPUT FROM AND
!    OUTPUT TO STACK
!
!    D. TUDHOPE/ROE
!
!- *
ARGSCIR
LET DSCL_I=ARGSCIR_IMAGEN
IF DSCL_I.EQ.0 THEN GOTO ERROR                    ! error in cursor, give up
IF P1.NES."" THEN LET OUTSETP_NEWVAL='P1'         ! LEAVE ALONE IF NO ARGUMENT
LET OUTSETP_INPICT=$
LET OUTSETP_OUTPICT=$
LET OUTSETP_CX=ARGSCIR_CX
LET OUTSETP_CY=ARGSCIR_CY
LET OUTSETP_DIAM=ARGSCIR_DIAM
OUTSETP
CLEAR OUTSETP_NEWVAL
EXIT
ERROR:
WRITE SYS$OUTPUT "PROCEDURE ABANDONED"
