!+
!      PROCEDURE   *** PUTDOC ***
!
!      IT TAKES A DOCUMEMENTATION FILE AND STUFFS IT INTO
!      THE FORTRAN SOURCE FILE, TOGETHER WITH SUITABLE
!      MODIFICATIONS TO THE C+ COMMENTS.
!
!      IT ALSO TIDIES THE FILES
!
!
!      ****** IT SHOULD ONLY BE USED FOR PROGRAMS ******
!      ****** IT DOES NOT WORK FOR PROCEDURES YET ******
!
!      IT TAKES A SINGLE (OPTIONAL) PARAMETER, WHICH IS THE NAME
!      OF THE PROGRAM BEING DOCUMENTED.
!

IF P1.EQS."" THEN INQUIRE P1 "PROGRAM NAME?"
ASSIGN 'P1'.FOR FOR001
ASSIGN 'P1'.DOC FOR002
ASSIGN 'P1'.NEW STUFFOUT
RUN ASPDIR:STUFF
ERUN:==@ASPDIR:EDITIT
ERUN 'P1'.DOC
PURGE 'P1'.*
DELETE 'P1'.FOR;*
RENAME 'P1'.NEW 'P1'.FOR
