!+	Procedure SETALL
!
!	allows IAM parameters to be changed
!	part of IAM suite
!	SETALLP returning results to IAMANAL
!
!	D. Tudhope/ROE/Sept 1982
!     A C Davenhall./ROE/18.1.84.  {Modified.}
!
!- *
SETALLP
LET IAMANAL_SKY=SETALLP_SKY
LET IAMANAL_THRLD=SETALLP_THRLD
LET IAMANAL_AREA=SETALLP_AREA
LET IAMANAL_SKYMAG=SETALLP_SKYMAG
LET SETPERP_SKY=SETALLP_SKY
LET PLOTQTH_THRLD=SETALLP_THRLD
