!+	Procedure SINCFIL
!
!	Multiply a fourier transform image by a SINC function
!	image assumed to have been generated by DFFTASP as here
!	assumed that zero frequency lies at IXEXT/2-1,IYEXT/2
!	in args coords 0..511
!
!       USES SINCFIL WITH INPUT FROM AND OUTPUT TO STACK
!
!	D. TUDHOPE/ROE
!
!- *
IF P1.NES."" THEN LET SINCFILP_SPREAD='P1'         ! LEAVE ALONE IF NO ARGUMENT
LET SINCFILP_INPICT=$
LET SINCFILP_OUTPICT=$
SINCFILP
CLEAR SINCFILP_SPREAD
