!+
!      PROCEDURE *** UNDOC ***
!
!      THIS TAKES OUT MOST OF THE DOCUMENTATION PUT INTO A PROGRAM
!      BY PROCEDURE PUTDOC.
!      ( IT LEAVES SOME BLANK LINES BEHIND )
!
!      IT SHOULD BE DONE BEFORE REPEATING THE DOCUMENTATION EXERCISE,
!      OTHERWISE SEVERAL COPIES OF THE DOCUMENTATION WILL FIND THEIR
!      WAY INTO THE SOURCE.
!
!      ******IT ONLY WORKS FOR PROGRAMS******
!      ******IT SHOULD NOT BE USED FOR PROCEDURES YET******
!
!      IT HAS A SINGLE OPTIONAL PARAMETER WHICH IS THE NAME
!      OF THE PROGRAM BEING DOCUMENTED.
!
!      WRITTEN BY K F HARTLEY AT RGO ON 17/12/81
!
IF P1.EQS."" THEN INQUIRE P1 "PROGRAM NAME?"
      ASSIGN 'P1'.FOR UNDOCIN
      ASSIGN 'P1'.NEW UNDOCOUT
      RUN ASPDIR:STRIP
      DELETE 'P1'.FOR;*
      RENAME 'P1'.NEW 'P1'.FOR;1
