	PROGRAM APANG

*+
*
*  - - - - - - -
*  :  A P A N G :
*  - - - - - - -
*
*
*   ARGS TRACKERBALL/CURSOR PAN AND ZOOM GENERAL PACKAGE
*
*
*	EXECUTION CONTINUES UNTIL BUTTON 4 IS PRESSED
*
*	BUTTON 2 INCREASES THE X ZOOM FACTOR
*	BUTTON 3 INCREASES THE Y ZOOM FACTOR
*	BUTTON 1 RESETS THE ZOOM FACTORS AND IMAGE POSITION
*
*
*	RETURNED
*
*	IX,IY POSITION OF CURSOR ON IMAGE
*
*
*    D.J.KING   R.G.O.   DEC 81
*
*-
	INTEGER STATUS,AX,AY
	REAL UX,UY

*  ALLOCATE ARGS

	CALL SRINIT(0,.FALSE.,STATUS)
	IF (STATUS.NE.0) THEN
		CALL WRERR('NOARGS')
	ELSE
		CALL ASP_PANG(AX,AY,UX,UY)
	ENDIF

* SEND COORDS TO ENVIRONMENT

	CALL WRKEYI ('AX',AX,1,STATUS)
	CALL WRKEYI ('AY',AY,1,STATUS)
	CALL WRKEYR ('X',UX,1,STATUS)
	CALL WRKEYR ('Y',UY,1,STATUS)

	END

