	PROGRAM ARESET
C
C+	PROGRAM TO COMPLETELY RESET THE ARGS DISPLAY
C
C	NO ARGUMENTS
C       RESETS THE ARGS CURRENTLY ASSIGNED TO ARGS_DEVICE
C
C	WFL JAN 1981 MODIF JULY 1981 TO ACCESS ARGS DATABASE
C
C
C-
C
	INTEGER ISTAT
C
	CALL SRINIT(0,.TRUE.,ISTAT)
	IF (ISTAT.EQ.0) THEN
		CALL ARGS_CLRIM(ISTAT)
	ENDIF
	CALL EXIT
	END
