	PROGRAM BLINKER

*+
*
*  - - - - - - - - -
*  :  B L I N K E R :
*  - - - - - - - - -
*
*
*   ARGS TRACKERBALL/CURSOR BLINK TWO 8 BIT IMAGES
*
*
*	EXECUTION CONTINUES UNTIL BUTTON 4 IS PRESSED
*
*	BUTTON 2 DISPLAYS THE FIRST IMAGE  (RESETS AUTO BLINK RATE)
*	BUTTON 3 DISPLAYS THE SECOND IMAGE  (RESETS AUTO BLINK RATE)
*	BUTTON 1 AUTO BLINK - BLINK RATE HALVED EACH TIME BUTTON PRESSED
*
*	THE SECOND IMAGE MAY BE MOVED RELATIVE TO THE FIRST
*	IMAGE BY MEANS OF THE TRACKER BALL
*
*	RETURNED
*
*	IX,IY POSITION OF THE FIRST IMAGE RELATIVE TO THE SECOND IMAGE
*
*
*    D.J.KING   R.G.O.   OCT 81
*
*-
	INTEGER STATUS,AX,AY

*  ALLOCATE ARGS
	CALL SRINIT(0,.FALSE.,STATUS)
	IF (STATUS.NE.0) THEN
		CALL WRERR('NOARGS')
	ELSE

		CALL ASP_BLINK(AX,AY)
		CALL SRSEND
*
		CALL WRKEYI ('AX',AX,1,STATUS)
		CALL WRKEYI ('AY',AY,1,STATUS)

	ENDIF

	END

