*
*+ CDIV  SCALAR  IMAGEIN  IMAGEOUT
*
*  DIVIDE EVERY ELEMENT OF IMAGEIN BY SCALAR GIVING IMAGEOUT
*

      INTEGER IDIMN(99)
      INCLUDE 'INTERIM(FMTPAR)'
      CALL RDKEYR('SCALAR',.FALSE.,1,SCALAR,NVALS,JSTAT)
      IF (ABS(SCALAR).LT.1E-20) GO TO 99
      CALL RDIMAG('IN',FMT_R,99,IDIMN,NDIMS,IPIN,JSTAT)
      CALL WRIMAG('OUT',FMT_R,IDIMN,NDIMS,IPOUT,JSTAT)
      NELS=1
      DO I=1,NDIMS
         NELS=NELS*IDIMN(I)
      END DO
      CALL CDIV(NELS,SCALAR,%VAL(IPIN),%VAL(IPOUT))
      CALL FRDATA(' ',JSTAT)
      GO TO 999

 99   CONTINUE
      CALL WRUSER('UNACCEPTABLE DIVISOR!',JSTAT)

 999  CONTINUE
      END
      SUBROUTINE CDIV(NELS,SCALAR,A,B)
      INTEGER NELS
      REAL SCALAR,A(NELS),B(NELS)
      DO I=1,NELS
         B(I)=A(I)/SCALAR
      END DO
      END
