C+
C   PROGRAM TO FIND THE CENTRE OF GRAVITY (FIRST MOMENT) OF A 1
C   OR 2-D IMAGE AND WRITE IT TO THE ENVIRONMENT.
C
C   PARAMETERS    1) INPUT	IMAGE
C                 2) XC	POSITION OF COG IN 1ST DIM (IN RANGE [0,SIZE-1])
C                 3) YC	IF 2D, AS FOR XC BUT IN 2ND DIM
C                 4) QUIET	LOGICAL, IFF TRUE NO REPORTING TO THE TERMINAL
C
C   CDP/RGO 7/5/81
C   'QUIET' PARAMETER ADDED OCT 1981 WFL
C-
      INTEGER PIN,AXIN(2)
      LOGICAL QUIET
      INCLUDE 'INTERIM(ERRPAR)'
      INCLUDE 'INTERIM(FMTPAR)'
C
C   GET IMAGE NAME
C
      ITRY = 0
    1 CALL RDIMAG('INPUT',FMT_R,2,AXIN,IDIM,PIN,ISTAT)
      IF(ISTAT.NE.ERR_NORMAL)  THEN
         CALL CNPAR('INPUT',ISTAT)
         IF(ITRY.EQ.0)   THEN
            ITRY=1
            GO TO 1
         ENDIF
         CALL EXIT
      ENDIF
C
C    AND READ QUIET PARAMETER
C
      CALL RDKEYL('QUIET',.FALSE.,1,QUIET,I,ISTAT)
      IF(ISTAT.NE.ERR_NORMAL) THEN
         QUIET=.FALSE.
      ENDIF
C
C    CALL COG ROUTINE
C
      CALL CALC_COG(%VAL(PIN),AXIN,QUIET)
      CALL FRDATA('INPUT',ISTAT)
      CALL EXIT
      END
C
      SUBROUTINE CALC_COG(DATA,AXIN,QUIET)
      INTEGER AXIN(2)
      LOGICAL QUIET
      REAL DATA(AXIN(1),AXIN(2))
      CHARACTER*30 OUT
      TOTDX=0.0
      TOTDY=0.0
      TOTD=0.0
      DO 100 J=1,AXIN(2)
      DO 100 I=1,AXIN(1)
      TOTDX = TOTDX + DATA(I,J)*(I-1)
      TOTDY = TOTDY + DATA(I,J)*(J-1)
      TOTD = TOTD + DATA(I,J)
  100 CONTINUE
      XCEN = TOTDX/TOTD
      YCEN = TOTDY/TOTD
C
C  OUTPUT RESULTS
C
      WRITE(OUT,'(2X,''X CENTROID = '',F6.2)') XCEN
      IF (.NOT.QUIET) CALL WRUSER(OUT,ISTAT)
      CALL WRKEYR('XC',XCEN,1,ISTAT)
      IF(AXIN(2).GT.1)  THEN
         WRITE(OUT,'(2X,''Y CENTROID = '',F6.2)') YCEN
         IF (.NOT.QUIET) CALL WRKEYR('YC',YCEN,1,ISTAT)
         CALL WRUSER(OUT,ISTAT)
      ENDIF
      RETURN
      END
