      PROGRAM COLCYCLE
*+
*     Program:-  COLCYCLE.
*
*
*                       +-------------+
*                       |             |
*                       |  COLCYCLE.  |
*                       |             |
*                       +-------------+
*
*
*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
*
*
*  Purpose:-
*   Take a colour table held as a Starlink image and from it generate
*   another colour table consisting of several cyclic replicas of the
*   original colour table.
*
*
*  Usage:-
*   Both the input and output colour tables are held as Starlink
*   images, they may be sent to an Args using LUTREAD.
*      The user is prompted for the filenames of the input and
*   output colour tables and the number of cycles to appear in the
*   output table. An output table consisting of the specified
*   number of replicas of the original table is generated.
*      It should be noted that the compressed cycles of the output
*   colour table are generated by averaging strips of the input
*   table, not by extracting singles value from it. Thus repeated
*   use of COLCYCLE will result in the output colour table becoming
*   "washed out" rather than discontinuous.
*
*
*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
*
*
*  Subroutines called;
*   E2D:-  COLCYS.
*
*  A C Davenhall./ROE/                                     26/10/82.
*-
      CALL COLCYS
      END
