      PROGRAM COLSLICE
*+
*     Program:- COLSLICE.
*
*
*                         +------------+
*                         |            |
*                         |  COLSLICE. |
*                         |            |
*                         +------------+
*
*
*  Purpose:-
*   Generate a file containing a colour table consisting of a monochromatic
*   ramp.
*
*
*  General Description:-
*     COLSLICE is used to generate a file containing a colour table
*   consisting of a monochromatic ramp varying from 0 intensity in
*   each of the three guns (black) to a user defined maximum intensity.
*     The user is prompted for the name of the file to hold the colour
*   table and then the intensity in each of the three guns (red, green,
*   blue) corresponding to the brightest intensity in the ramp. The
*   colour table is then generated by linearly interpolating intermediate
*   intensities between the maximum intensity and black, corresponding
*   to the lowest level in the table.
*     The colour table file generated can be sent to the Args using
*   LUTREAD.
*
*
*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
*
*
*  Subroutines called;
*   COLSLICS.
*
*  A C Davenhall./ROE/                                         28/2/83.
*-
      CALL COLSLICS
      END
