C     -----------------
C ROUTINE TO SEND ORDERS TO THE ARGS THAT HAVE BEEN SPECIFIED IN HEX.
C FACILITIES:
C   READ HEX FROM TERMINAL OR NAMED FILE
      PARAMETER STRTM=5, STWTM=6, STHEX=9
      INTEGER FAIL,OPCODE
      CHARACTER*4 HEX
C   FILENAME VARIABLES.
      CHARACTER*80 FULLFN
      CHARACTER*20 FN
      CHARACTER*60 PREF
      CHARACTER*4  SUFF
      DATA SUFF/'.HEX'/
C   INITIALISE
      CALL SRINIT(0,.FALSE.,FAIL)
      IF( FAIL.NE.0 ) STOP 'ARGS NOT AVAILABLE'
      PREF=' '
      CALL RDKEYC('DRNAME',.TRUE.,1,PREF,JUNK,STATUS)
C   LOOP INDEFINITELY. EACH CYCLE, READ A COMMAND AND ACT UPON IT.
 400        CALL GETC('FLNAME',FN)
            FULLFN=PREF(1:INDEX(PREF,' ')-1)//FN(1:INDEX(FN,' ')-1)//
     1         SUFF
            OPEN(UNIT=STHEX, NAME=FULLFN, READONLY, TYPE='OLD', ERR=420)
            GOTO 1000
C         FILENAME ERROR
 420        WRITE(STWTM,'('' PROBLEM WITH FILENAME '',A)' )FULLFN
	STOP
 1000       CONTINUE
              READ(STHEX,'(A4)',END=1200) HEX
              IF( HEX.EQ.'END') GOTO 1200
              READ(UNIT=HEX,FMT='(Z4)',ERR=1050)OPCODE
              CALL ARGS_FLUSH(1)
              CALL ARGS_PUT1(OPCODE)
              GOTO 1000
C           HERE: CONVERSION ERROR
 1050         WRITE(STWTM,'('' CONVERSION ERROR IN LINE '',A4)')HEX
              GOTO 1200
C   HERE, END OF FILE.
 1200  CALL ARGS_FLUSH(-1)
      END
C-------------------------------------------------------------
C
      SUBROUTINE GETC(NAME,VALUE)
C     ---------------------------
C FETCH CHARACTER STRING FROM STARLINK ENVIRONMENT INPUT.
C ARGUMENTS:
C   NAME   (ENTRY) PROMPT
C   VALUE  (EXIT)  STRING RETURNED TO CALLER.
      IMPLICIT INTEGER (A-Z)
      CHARACTER*(*) NAME,VALUE
C
      CALL RDKEYC(NAME,.TRUE.,1,VALUE,JUNK,STATUS)
      END
