      PROGRAM IAMHELP

C+
C    PROGRAM IAMHELP
C	short help listing for IAM suite of programs
C
C  D. Tudhope/ROE/Sept 1982
C
C-

      CHARACTER*1 C

      CALL WRUSER(' IAM SUITE OF PROGRAMS TO PRODUCE PARAMETERISED',I)
      CALL WRUSER('         DATA FROM IMAGE FRAMES OF *ANY* SIZE',I)
      CALL WRUSER(' ',I)
      CALL WRUSER(' GRAPHICS ON ARGS IF WANTED',I)
      CALL WRUSER('       ANALYSER HAS 4 USER-DEFINABLE VARIABLES:',I)
      CALL WRUSER('  AREA   (I) SMALLEST NO. OF PIXELS IN OBJECT',I)
      CALL WRUSER('  SKY    (R) SKY BACKGROUND LEVEL',I)
      CALL WRUSER('  THRLD  (R) THRESHOLD CUT FOR OBJECTS',I)
      CALL WRUSER('  SKYMAG (R) SKY BACKGROUND MAG. IN ONE PIXEL',I)
      CALL WRUSER('       AREA DEFAULTED TO 10 AND SKYMAG TO 0.0',I)
      CALL WRUSER(' SKY, THRLD MUST BE SET BEFORE RUNNING ANALYSER',I)
      CALL WRUSER('  EITHER BY TYPING IN VALUES (SET-)',I)
      CALL WRUSER('  OR WITH CURSOR ON INTENSITY HISTOGRAM (GET-)',I)
      CALL WRUSER(' DIFFERENT RANGES OF HISTOGRAM CAN BE PLOTTED',I)
      CALL WRUSER(' THE LIMITS CAN BE CHANGED WITH SETLIM,GETLIM',I)
      CALL WRUSER('  AND THEN HISTOGRAM REPLOTTED WITH IAMHIS',I)
      CALL WRUSER(' IF YOU WANT TO CLEAR LIMITS FOR A HISTOGRAM OF',I)
      CALL WRUSER(' A NEW IMAGE (NOT COMPULSARY) THEN RUN CLRLIM',I)
      CALL WRUSER(' OUTPUT OF ANALYSER IS A "PARAMS" FILE',I)
      CALL WRUSER('  CONTAINING ALL OBJECTS FOUND BY ANALYSER',I)
      CALL WRUSER('  AND WHICH CAN BE OUTPUT ON ARGS,VERSATEK OR .LP',I)
C*  a screen full
      CALL READC('REPLY','     hit RETURN to continue',' ',' ','~',C,I)
C*  new screen full
      CALL WRUSER(' 	commands',I)
      CALL WRUSER(' IAMHELP -- THIS HELP INFO',I)
      CALL WRUSER(' 	intensity histogram',I)
      CALL WRUSER(' IAMHIS  -- PLOT HISTOGRAM ON ARGS QUADRANT',I)
      CALL WRUSER(' SETLIM  -- TYPE NEW RANGE OF HISTOGRAM',I)
      CALL WRUSER(' GETLIM  -- GET RANGE USING CURSOR ON HISTOGRAM',I)
      CALL WRUSER(' CLRLIM  -- CLEAR HISTOGRAM RANGE FOR NEW IMAGE',I)
      CALL WRUSER(' 	setting area,sky,thrld,skymag',I)
      CALL WRUSER(' SETAREA -- TYPE NEW AREA CUT',I)
      CALL WRUSER(' SETMAG  -- TYPE NEW SKY MAGNITUDE',I)
      CALL WRUSER(' SETPER  -- TYPE THRLD AS % ABOVE SKY',I)
      CALL WRUSER(' SETALL  -- TYPE NEW AREA,SKY,THRLD,SKYMAG',I)
      CALL WRUSER(' GETSKY  -- GET SKY USING CURSOR ON HISTOGRAM',I)
      CALL WRUSER(' GETTHR  -- GET THRLD USING CURSOR ON HISTOGRAM',I)
      CALL WRUSER(' 	plotting image on args',I)
      CALL WRUSER(' APLOT   -- PLOT IMAGE ON FULL ARGS SCREEN',I)
      CALL WRUSER(' APLOTQ  -- PLOT IMAGE ON ARGS QUADRANT',I)
      CALL WRUSER(' CLRQUAD -- CLEAR ARGS QUADRANT',I)
      CALL WRUSER(' PLOTQTH -- THRESHOLD IMAGE (THRLD) ON QUADRANT',I)
      CALL WRUSER(' 	run analyser with variables set',I)
      CALL WRUSER(' IAMANAL -- RUN ANALYSER, OUTPUT TO PARAMS FILE',I)
      CALL WRUSER(' 	outputing objects found by  analyser',I)
      CALL WRUSER(' IGPLOT  -- PLOT ONTO ARGS QUAD (EG OVER PLOTQTH)',I)
      CALL WRUSER(' IGJOB   -- PRODUCE VERSATEK PLOT FILE',I)
      CALL WRUSER(' IAMPR   -- PRINT LIST OF OBJECTS ON .LP',I)
      END
