*
*+ MULT  IMAGEIN1  IMAGEIN2  IMAGEOUT
*
*  THE PRODUCT IMAGEIN1*IMAGEIN2 IS STORED IN IMAGEOUT
*

      INTEGER IDIMN1(99),IDIMN2(99)

      INCLUDE 'INTERIM(FMTPAR)'

      CALL RDIMAG('IN1',FMT_R,99,IDIMN1,NDIMS1,IPIN1,JSTAT)
      CALL RDIMAG('IN2',FMT_R,99,IDIMN2,NDIMS2,IPIN2,JSTAT)
      IF (NDIMS1.NE.NDIMS2) GO TO 9010
      NELS = 1
      DO I = 1,NDIMS1
         ID = IDIMN1(I)
         IF (IDIMN2(I).NE.ID) GO TO 9010
         NELS = NELS*ID
      END DO
      CALL WRIMAG('OUT',FMT_R,IDIMN1,NDIMS1,IPOUT,JSTAT)
      CALL MULT(NELS,%VAL(IPIN1),%VAL(IPIN2),%VAL(IPOUT))
      GO TO 9999

 9010 CONTINUE
      CALL WRUSER('IMAGES MUST BE OF SAME ORDER!',JSTAT)

 9999 CONTINUE
      CALL FRDATA(' ',JSTAT)
      END
      SUBROUTINE MULT(NELS,A,B,C)
      INTEGER NELS
      REAL A(NELS),B(NELS),C(NELS)
      DO I = 1,NELS
         C(I)=A(I)*B(I)
      END DO
      END
