*
*+  PSPEC IN1 IN2 OUT
*
*   Calculate power spectrum of IN1 and IN2.
*
*   WFL Aug 81

      INCLUDE 'INTERIM(FMTPAR)'
      INCLUDE 'INTERIM(ERRPAR)'

      INTEGER AXIS(99),NAXIS,IN1PTR,IN2PTR,STATUS,OUTPTR,NELS,I

      CALL RDIMAG('IN1',FMT_R,99,AXIS,NAXIS,IN1PTR,STATUS)
      IF (STATUS.NE.ERR_NORMAL) THEN
          CALL WRERR('BADIN1')
          CALL EXIT
      ENDIF

      CALL RDIMAG('IN2',FMT_R,99,AXIS,NAXIS,IN2PTR,STATUS)
      IF (STATUS.NE.ERR_NORMAL) THEN
          CALL WRERR('BADIN2')
          CALL EXIT
      ENDIF

      CALL WRIMAG('OUT',FMT_R,AXIS,NAXIS,OUTPTR,STATUS)
      IF (STATUS.NE.ERR_NORMAL) THEN
          CALL WRERR('BADOUT')
          CALL EXIT
      ENDIF

      NELS=1
      DO I=1,NAXIS
          NELS=NELS*AXIS(I)
      ENDDO
      CALL PSPEC2(%VAL(IN1PTR),%VAL(IN2PTR),NELS,%VAL(OUTPTR))

      END

      SUBROUTINE PSPEC2(IN1,IN2,NELS,OUT,STATUS)

      INTEGER NELS
      REAL IN1(NELS),IN2(NELS),OUT(NELS)

      DO I=1,NELS
          OUT(I)=IN1(I)*IN1(I)+IN2(I)*IN2(I)
      ENDDO

      END
