	PROGRAM RDLIST
*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*PURPOSE
*	TO PRINT THE CONTENTS OF AN RA,DEC LIST DATASET
*
*METHOD
*	OBTAIN INPUT DATASET. PRINT TITLE IF PRESENT. CALL RADLST TO
*	PRINT THE DATA AND STORE ID,RA,DEC IN THE FILE RDOUT.LIS
*
*ARGUMENTS
*	NONE
*
*STARLINK PARAMETERS
*	INPUT
*		THE INPUT RA,DEC LIST DATASET
*
*CALLS
*	THIS PACKAGE:
*		GTXYLR,GTDSCR
*	STARLINK:
*		WRUSER,FRDATA
*
*NOTES
*	USES VAX %VAL FACILITY
*       TO OBTIAN A HARD COPY OF THE LIST PRINT OUT THE FILE RDOUT.LIS
*
*WRITTEN BY
*	B HARRISON  RGO		Version 1	July 1982
*-----------------------------------------------------------------------



C
C 	Based on the program XYLIST by  R. F. Warren-Smith
C
      CHARACTER CVAL*1,TITLE*30
C
C OPEN THE FILE RDOUT.LIS TO ACCEPT RA,DEC AND ID
C
	OPEN(UNIT=1,FILE='RDOUT.LIS',STATUS='NEW')
C
C OBTAIN INPUT RA,DEC LIST
C
      CALL GTXYLR('INPUT',.FALSE.,NITEM,LSTLEN,IPIN,IERRXY)
      IF(IERRXY.EQ.0) THEN
C
C INPUT SUCCESSFULLY OBTAINED... EXTRACT TITLE
C
	TITLE=' '
	CALL GTDSCR('INPUT','TITLE','CHARACTER',IVAL,RVAL,TITLE,IERR)
C
C IF TITLE PRESENT, PRINT IT
C
	CALL WRUSER(' ',ISTAT)
	WRITE(1,906)TITLE
906  	FORMAT(1H ,T20,'TITLE :',A)
	CALL WRUSER(' ',ISTAT)
	WRITE(1,900) PRBUF
	IF(TITLE.NE.' ') THEN
	  CALL WRUSER('                      TITLE: '//TITLE,ISTAT)
	WRITE(1,900)PRBUF
	  CALL WRUSER(' ',ISTAT)
	WRITE(1,900)PRBUF
	ENDIF
C
C CALL RADLST TO PRINT THE CONTENTS OF THE LIST
C
	CALL RADLST(%VAL(IPIN),NITEM,LSTLEN)
      ENDIF
C
C FREE DATA AREA AND RETURN
C
      CALL FRDATA(' ',ISTAT)
C
C	Close the file RDOUT.LIS
C
	CLOSE(UNIT=1)
900	FORMAT(1H ,A)
      END

      SUBROUTINE RADLST(LIST,NITEM,LSTLEN)
*
*PURPOSE
*	TO PRINT THE CONTENTS OF AN RA,DEC LIST DATASET
*
*METHOD
*	PRINT TITLE AND HEADINGS, PRINT TABLE OF IDENTIFIERS, RA,DEC
*	POSITIONS AND MAGNITUDES IF PRESENT. PRINT TOTAL NUMBER OF
*	ENTRIES IN LIST.
*
*ARGUMENTS
*	LIST (IN)
*	INTEGER(NITEM,LSTLEN)
*		THE INPUT RA,DEC LIST
*	NITEM,LSTLEN (IN)
*	INTEGER
*		DIMENSIONS OF LIST
*
*CALLS
*	STARLINK:
*		WRUSER
*
*NOTES
*	USES BYTE ARRAYS
*
*WRITTEN BY
*        B HARRISON	RGO	Version 1	July 1982
*


C
C 	Based on the program XYLIST by R. F. Warren-Smith    Durham
C
C SET MAX NUMBER OF ITEMS TO BE PRINTED
C
      PARAMETER (MAXITM=8)
      INTEGER*4 LIST(NITEM,LSTLEN),BUF(MAXITM)
      BYTE ASC(20)
      REAL INFO(MAXITM-5)
C
C SET EQUIVALENCE SO THAT FIRST 20 BYTES ARE ACCESSED AS BYTE
C DATA AND SUBSEQUENT DATA IS REAL*4
C
      EQUIVALENCE (BUF(1),ASC(1)),(BUF(6),INFO(1))
      CHARACTER ID*20,TITLE(MAXITM-5)*35,ULINE(MAXITM-5)*35,PRBUF*80
      DATA TITLE/'   R.A.      ','        DEC.      ','        '/
      DATA ULINE/'   ----     ','        ----   ','       '/
C
C	Open the file RDOUT.LIS
C
	OPEN(UNIT=1,FILE='RDOUT.LIS',STATUS='NEW')
C
C NINFO IS THE NUMBER OF NON-CHARACTER ITEMS TO BE PRINTED
C
      NINFO=MIN(MAXITM,NITEM)-5
C
C PRINT TITLES AND UNDERLINING TO TERMINAL AND THE FILE RDOUT.LIS
C
      WRITE(PRBUF,10)(TITLE(L),L=1,NINFO)
   10 FORMAT(' IDENTIFIER',T27,20A14)
      CALL WRUSER(PRBUF,ISTAT)
	WRITE(1,900) PRBUF
900	FORMAT(1H ,A)
      WRITE(PRBUF,11)(ULINE(L),L=1,NINFO)
   11 FORMAT(' ----------',T27,20A14)
      CALL WRUSER(PRBUF,ISTAT)
	WRITE(1,900) PRBUF
	PRINT *,'                          H  M  S            D  M  S'
	CALL WRUSER(' ',ISTAT)
	CALL WRUSER(' ',ISTAT)
    	WRITE(1,911)
	WRITE(1,910)
911	FORMAT(1H ,T29,'H  M  S            D  M  S')
910	FORMAT(1H ,' ')
C
C SCAN THROUGH LIST ENTRIES
C
      DO 98 J=1,LSTLEN
C
C COPY ENTRY INTO BUFFER TO ALLOW DIFFERENT DATA TYPES
C
	DO 97 I=1,MIN(NITEM,MAXITM)
	BUF(I)=LIST(I,J)

   97   CONTINUE
C
C CONVERT IDENTIFIER BYTES TO CHARACTERS
C
        DO 96 I=1,20
	  NCHAR=ASC(I)
	  ID(I:I)=CHAR(NCHAR)
   96	CONTINUE
C
C PRINT A LINE OF INFORMATION
C
	 RAS=INFO(1)
	DECS=INFO(2)
C
C	Call DECODE to convert to  hrs,mins,secs and deg,mins,secs.
C
	CALL DECODE(RAS,DECS,IHRAS,IAMAS,SRAS,IDDECS,IMDECS,SDECS,FLAG)
C
C	Note the use of FLAG to test to see if the declination is
C	negative so we obtain the correct print out to terminal
C	and file.
C
	IF(FLAG.EQ.0.0) THEN
	WRITE(PRBUF,12)ID,IHRAS,IAMAS,SRAS,IDDECS,IMDECS,SDECS
   12   FORMAT(' ',A20,T27,I2,' ',I2,' ',F5.2,'       ',
     :	I3,' ',I2,' ',F5.2)
	ENDIF
	IF (FLAG.EQ.1.0) THEN
	WRITE(PRBUF,15)ID,IHRAS,IAMAS,SRAS,IDDECS,IMDECS,SDECS
   15	FORMAT(' ',A20,T27,I2,' ',I2,' ',F5.2,'       ',
     :	'-',I2,' ',I2,' ',F5.2)
	ENDIF
	CALL WRUSER(PRBUF,ISTAT)
        WRITE(1,900) PRBUF
   98 CONTINUE
C
C FINALLY PRINT THE NUMBER OF ENTRIES
C
	WRITE(1,901)
      CALL WRUSER(' ',ISTAT)
      IF(LSTLEN.NE.1) THEN
	WRITE(PRBUF,13)LSTLEN
   13   FORMAT(T22,I7,' LIST ENTRIES')
        CALL WRUSER(PRBUF,ISTAT)
	WRITE(1,900) PRBUF
      ELSE
	CALL WRUSER('                            1 LIST ENTRY',ISTAT)
	WRITE(1,900) PRBUF
901	FORMAT(1H ,//)
      ENDIF
	CLOSE(UNIT=1)
      RETURN
      END
