C+
C  program SINCFILP
C
C    Multiply a fourier transform image by a SINC function
C    image assumed to have been generated by DFFTASP as here assumed that
C    zero frequency lies at IXEXT/2-1,IYEXT/2 in args coords 0..511
C    calls SINFILSUB to do it
C
C  Given (program parameters)
C    INPICT (RA)   image to be modified
C    SPREAD  (R)   width of sinc spread
C
C  Returned (program parameters)
C    OUTPICT  (RA)  modified image
C
C  D. Brownrigg, D. Tudhope  ROE  1981
C-

      REAL SPREAD
      INTEGER NAXIN(2),NAXOUT(2),NPIN,NPOUT,ISTATUS
      REAL XCN,YCN

      ISTATUS=0
      CALL INPICR('INPICT','GIVE INPUT IMAGE',2,NAXIN,NPIN,ISTATUS)
      NAXOUT(1)=NAXIN(1)
      NAXOUT(2)=NAXIN(2)
      CALL OUTPICR('OUTPICT','GIVE OUTPUT IMAGE',2,NAXOUT,NPOUT,ISTATUS)
      CALL READR('SPREAD','GIVE WIDTH FOR SINC SPREAD',
     :           20.0,0.0,256.0,SPREAD,ISTATUS)
      IF (ISTATUS.NE.0) THEN
         CALL WRERR('MISREAD')
      ELSE
       CALL COPY(NAXIN(1),NAXIN(2),%VAL(NPIN),
     &     NAXOUT(1),NAXOUT(2),%VAL(NPOUT))
       XCN=NAXOUT(1)/2.0 - 1.0
       YCN=NAXOUT(2)/2.0
       CALL SINFILSUB(XCN,YCN,SPREAD,NAXOUT(1),NAXOUT(2),%VAL(NPOUT))
      ENDIF
      END
