C+
C
C  STARLINK PROGRAM TO CREATE A STARLINK 1D IMAGE FROM DATA TYPED
C  IN AT THE TERMINAL.
C
C  PARAMETERS     1) NO OF POINTS TO INPUT (NPTS)
C                 2) OUTPUT IMAGE
C                 3) FIRST DATA POINT
C                 .
C                 .
C                 NPTS+2) LAST DATA POINT
C
C     CDP/RGO  7/5/81
C-
      REAL LINE(1024)
      INTEGER POUT
      INCLUDE 'INTERIM(ERRPAR)'
      INCLUDE 'INTERIM(FMTPAR)'
C
C   GET THE TOTAL NO OF POINTS TO READ IN
C
      NVAL = 1
      CALL RDKEYI('NPTS',.FALSE.,1,NPTS,NVAL,ISTAT)
      IF(ISTAT.NE.ER_NORMAL) THEN
         CALL CNPAR('NPTS',ISTAT)
         CALL EXIT
      ENDIF
C
C   GET OUTPUT IMAGE NAME
C
      CALL WRIMAG('OUTPUT',FMT_R,NPTS,NVAL,POUT,ISTAT)
      IF(ISTAT.NE.ERR_NORMAL)  THEN
         CALL EXIT
      ENDIF
C
C  NOW LOOP TO PICK UP INDIVIDUAL POINTS
C
      DO 100 I=1,NPTS
      CALL RDKEYR('VALUE',.FALSE.,1,VALUE,NVAL,ISTAT)
      IF(ISTAT.NE.ERR_NORMAL)  THEN
         CALL EXIT
      ENDIF
      LINE(I) = VALUE
      CALL CNPAR('VALUE',ISTAT)
  100 CONTINUE
C
C   PUT DATA INTO IMAGE
C
      CALL IMAGE_OUT(%VAL(POUT),NPTS,LINE)
      CALL FRDATA('OUTPUT',ISTAT)
      CALL EXIT
      END
C
C
C
      SUBROUTINE IMAGE_OUT(DATA,NPTS,LINE)
      REAL DATA(NPTS),LINE(NPTS)
      DO 100 I=1,NPTS
      DATA(I) = LINE(I)
  100 CONTINUE
      RETURN
      END
