	SUBROUTINE ACURS(TYPE,NPOS,RADIUS,XPOS,YPOS,RET,CURCOL,INDCOL,RDATA)
	CHARACTER*1 CURCOL,INDCOL
	INTEGER TYPE,NPOS,RADIUS,XPOS,YPOS,RET,XOR,YOR
	INTEGER*2 DATA(9)
	INTEGER*2 OUTDATA(769)
	INTEGER RDATA(NPOS*3)
	CALL ARGS_RDIM(IXPOS,IYPOS,ISX,ISY,I,I,STATUS)
	XOR=IXPOS-(ISX/2)
	YOR=IYPOS-(ISY/2)
	IF (RADIUS.LE.0) RADIUS=10
	IF (XPOS.LE.0.OR.XPOS.GE.511) XPOS=255
	IF (YPOS.LE.0.OR.YPOS.GE.511) YPOS=255
	IF (TYPE.LE.0.OR.TYPE.GT.4) TYPE=1
	IF (NPOS.LE.0.OR.NPOS.GE.256) NPOS=1
	DATA(1)=TYPE
	DATA(2)=NPOS
	DATA(3)=RADIUS
	DATA(4)=XPOS
	DATA(5)=YPOS
	DATA(6)=XOR
	DATA(7)=YOR
	DATA(8)=ISX
	DATA(9)=ISY
	CALL ARGS_OVOP(9,CURCOL)
	CALL ARGS_OVC(1,INDCOL)
	CALL LOAD_UCUR
	CALL WRITE_UCUR(DATA)
	CALL RUN_UCUR
	CALL READ_UCUR(OUTDATA)
	DO I=1,NPOS*3
	RDATA(I)=OUTDATA(I)
	END DO
	RET=OUTDATA(769)
	CALL ARGS_OVCL(9,.FALSE.)
	END
