	SUBROUTINE ASP_CANQIO
C
C+	ROUTINE TO CANCEL ANY OUTSTANDING QIO REQUESTS ON THE TERMINAL
C	WHICH MAY HAVE BEEN LEFT DUE TO READING THE CURSOR WITH FINGS.
C
C	IN ADDITION, THE TERMINAL BUFFER IS EMPTIED, JUST IN CASE!
C
C	COMMON BLOCK ICHAN IS USED, SO THE ROUTINE WILL HAVE NO EFFECT
C	IF THE TERMINAL HAS NOT BEEN ASSIGNED USING FINGS
C
C	WFL RGO MAR 81
C
	IMPLICIT INTEGER*4 (S)
	COMMON/ICHAN/ICHAN
	INTEGER*2 ICHAN,I
	EXTERNAL IO$_READVBLK,IO$M_NOWAIT
	CHARACTER*1 BUFF
	I=IOR(%LOC(IO$_READVBLK),%LOC(IO$M_NOWAIT))
	SUCCESS=SYS$QIOW(,%VAL(ICHAN),%VAL(I),,,,%REF(BUFF),
     +	%VAL(1),,,,)
	IF (.NOT.SUCCESS) CALL SYS$EXIT(%VAL(SUCCESS))
	SUCCESS=SYS$CANCEL(%VAL(ICHAN))
	IF (.NOT.SUCCESS) CALL SYS$EXIT(%VAL(SUCCESS))
	RETURN
	END
