	SUBROUTINE ASP_BLINK(AX,AY)

	INTEGER IDMAX,STATUS,AX,AY
	INTEGER*2 ARGSIN(4),ARGSOUT(2)
	CHARACTER VALUE*80


* CHECK DATABASE TO FIND IF ANYTHING IS DISPLAYED
	CALL ARGS_NUMIM(IDMAX)
	IF (IDMAX.EQ.O) THEN
		CALL WRERR('NOIMS')
	ELSE

* GET INFORMATION ON LAST IMAGE DISPLAYED FROM DATABASE

		CALL ARGS_RDPAR('DISPZOOM',1,VALUE,NVALS,STATUS)
		CALL ASP_DZTOI('ZXC',VALUE,IXC,STATUS)
		CALL ASP_DZTOI('ZYC',VALUE,IYC,STATUS)
		CALL ASP_DZTOI('ZXF',VALUE,IXF,STATUS)
		CALL ASP_DZTOI('ZYF',VALUE,IYF,STATUS)

		IF (IXF.EQ.0) THEN
			IXF=1
			IYF=1
			IXC=256
			IYC=256
		ENDIF

* SET UP INFORMATION TO SEND TO ARGS PROGRAM

		ARGSIN(1) = IXF-1
		ARGSIN(2) = (IYF-1)*256
		ARGSIN(3) = IXC
		ARGSIN(4) = IYC
	

*  SET SYSTEM CURSOR
		CALL ARGS_CURS('+')
		CALL ARGS_CURC('I')

*  CENTRE CURSOR
		CALL ARGS_CURP(0,255,255)


*  SWITCH ON LAMPS
		CALL ARGS_LAMPS(1,1,1,1)

*  LOAD AND RUN ARGS PROGRAM
		CALL LOAD_BLINK
		CALL WRITE_BLINK(ARGSIN)
		CALL RUN_BLINK
		CALL READ_BLINK(ARGSOUT)

		AX=ARGSOUT(1)-256
		AY=ARGSOUT(2)-256

*  SWITCH OFF LAMPS
		CALL ARGS_LAMPS(0,0,0,0)

*  DISABLE CURSOR
		CALL ARGS_CURS('0')
	ENDIF

	END

