      SUBROUTINE CONTOUR(DEVICE,SIZE,HT,NH,STSAM,ENSAM,
     1                  STREC,ENREC,IDENS,IX,IY,ITITLE,
     1                  IBLK)
      INTEGER STSAM,ENSAM,STREC,ENREC
      REAL*4 IDENS(IX,IY)
      INTEGER*4 ITITLE(10)
      REAL*4 XD(2),YD(2),AX,AY,HT(30)
      CHARACTER CURPOS*15,DEVICE*4,CHEIGHT*40
      AX=24.0
      AY = AX * REAL(IY)/REAL(IX)
      IF(DEVICE.NE.'ARGS') CALL JBDEV(DEVICE)
      CALL PAGE(AX+4.0,AY+4.0)
      IF(DEVICE.NE.'STEK'.AND.DEVICE.NE.'ARGS') THEN
      AX = SIZE
      AY = AX * REAL(IY)/REAL(IX)
      ELSE
      ENDIF
      XD(1)=FLOAT(STSAM)
      XD(2)=FLOAT(ENSAM)
      YD(1)=FLOAT(STREC)
      YD(2)=FLOAT(ENREC)
      LC = 1 + ENSAM -STSAM
      LR = 1 + ENREC - STREC
      CALL JBAXES(XD,2,AX,'X-AXIS',6,YD,2,AY,'Y-AXIS',6)
      CALL TITLE(3,2,ITITLE,40)
      IF(IBLK.NE.1) THEN
      LC = LC/IBLK
      LR = LR/IBLK
      ENDIF
      DO 116 K=1,NH
	IF(DEVICE.EQ.'ARGS') THEN
	MP = MOD(K,10)+1
	ELSE
	MP = MOD(K,3)+1
	ENDIF
      CALL PEN(MP)
      WRITE(CHEIGHT,9999) HT(K)
9999  FORMAT('DRAWING CONTOUR AT HEIGHT', F8.1)
      CALL WRUSER(CHEIGHT,ISTATUS)
116   CALL LEVEL(HT(K),IDENS,XD(1),REAL(IBLK),LC,
     1                        YD(1),REAL(IBLK),LR)
      CALL BREAK
      CALL JOIN PT(XD(2),YD(2))
      IF(DEVICE.EQ.'STEK') THEN
      CALL CURDEF('A*.')
 400   CALL CURSOR(ICOM,XI,YI)
      IF(ICOM.EQ.1) RETURN
      CALL JVCPOS(XI,YI,XXX,YYY,XD(1),YD(1),
     1           XD(2),YD(2))
      WRITE(CURPOS,900) NINT(XXX),NINT(YYY)
900   FORMAT('X=',I5,' Y=',I5)
      CALL WRUSER(CURPOS,ISTAT)
      GO TO 400
      ENDIF
      CALL END PLT
      RETURN
      END
