	SUBROUTINE GEN_SETSYM(NAME,VALUE)
	IMPLICIT INTEGER (A-Z)
	CHARACTER*(*) NAME,VALUE
	CALL GEN_FLIMCS(NAME,NS,NL)
	CALL GEN_FLIMCS(VALUE,VS,VL)
	IF (VL.GT.0) THEN
		CALL GEN_CRELOG(NAME(NS:NS+NL-1),VALUE(VS:VS+VL-1))
		CALL WFL_SETSYM(NAME(NS:NS+NL-1),VALUE(VS:VS+VL-1))
	ELSE
		CALL GEN_DELLOG(NAME(NS:NS+NL-1))
		CALL WFL_SETSYM(NAME(NS:NS+NL-1),' ')
	ENDIF
	RETURN
	END
