      SUBROUTINE GETIMAG(NAME,FORMAT,MAXDIM,DIMENS,ACTDIM,PNTR,STATUS)
C
C++
C      GETIMAG - GET AN IMAGE DATASET
C
C      THIS ROUTINE IS BASICALLY ONE LEVEL HIGHER THAN THE STANDARD
C      ENVIRONMENT ROUTINE "RDIMAG"
C
C      IT SIMPLY PROVIDES A FREQUENTLY REQUIRED SEQUENCE OF CODE
C      WHERE THE USER IS ALLOWED TWO TRYS AT GETTING A VALID 
C      FRAME NAME .
C      IF THERE IS AN ERROR THE FIRST TIME A MESSAGE IS OUTPUT
C      THE PARAMETER IS CANCELLED AND RDIMAG CALLED AGAIN.
C      IF THERE IS STILL AN ERROR THE PROGRAM IS HALTED (CALL EXIT)
C                                 *********************
C
C      THE ONLY ACCEPTABLE ERROR CONDITION IS "ERR_NORMAL"
C      THERFORE NO USE IF DEFAULT FRAME NAME IS REQUIRED
C
C      ALL THE ARGUMENTS HAVE THE SAME MEANING AND TYPE AS 
C      FOR THE ROUTINE "RDIMAG" ( SEE SUN 4.1 )
C
C      WRITTEN AT RGO BY K F HARTLEY
C
C      VERSION #1
C
      IMPLICIT INTEGER (A-Z)
      CHARACTER*(*) NAME
      INTEGER*4 FORMAT,MAXDIM,DIMENS(MAXDIM),ACTDIM,PNTR,STATUS
C
C      INCLUDE DEFINITION OF ERROR PARAMETERS
C
      INCLUDE 'INTERIM(ERRPAR)'
C
C      FIRST CALL TO RDIMAG
C
      CALL RDIMAG(NAME,FORMAT,MAXDIM,DIMENS,ACTDIM,PNTR,STATUS)
      IF (STATUS.NE.ERR_NORMAL) THEN
         CALL WRUSER('ERROR IN FRAME NAME - PLEASE TRY AGAIN',STATUS)
         CALL CNPAR(NAME,STATUS)
         CALL RDIMAG(NAME,FORMAT,MAXDIM,DIMENS,ACTDIM,PNTR,STATUS)
         IF (STATUS.NE.ERR_NORMAL) THEN
            CALL WRUSER('YOU HAVE HAD YOUR TWO TRIES',STATUS)
            CALL FRDATA(' ',STATUS)
            CALL EXIT
         END IF
      END IF
      RETURN
      END
