      SUBROUTINE IZOOM(IX,IY,IFX,IFY)

*+  ZOOM ABOUT (IX,IY) WITH FACTORS (IFX,IFY) (ASSUMED LEGAL)
*
*   PTW - COMMENTS ADDED BY WFL JULY 1981

      INTEGER IX,IY,IFX,IFY
      CALL ARGS_FLUSH(4)
      CALL ARGS_PUT1('C000'X+IX)
      CALL ARGS_PUT1('A000'X+IY)
      CALL ARGS_PUT1('5001'X)
      CALL ARGS_PUT1(256*(IFY-1)+IFX-1)
      CALL SRSEND
      END
