	SUBROUTINE LIMITS2(INPUT,ISIZE,LLOG,LIMS)
C
C+	ROUTINE TO PLOT THE 1D ARRAY INPUT USING SIMPLEPLOT, THEN
C	READ TWO LIMITS USING THE CURSOR
C
C	ARGUMENTS	INPUT	INTEGER ARRAY	INPUT ARRAY
C			ISIZE	INTEGER		LENGTH OF INPUT
C			LLOG	LOGICAL		TRUE IFF LOG
C						DISPLAY NEEDED
C			LIMS	INTEGER ARRAY	SELECTED LIMITS
C
C	WFL FEB 1981 RGO
C
	INTEGER LIMS(2),STATUS
	REAL INPUT(0:ISIZE-1),XVALS(0:2047),YVALS(0:2047)
	CHARACTER LR(2)*1,VAL*4
	LOGICAL LLOG
	DATA LR/'L','R'/
	ISIZEM1=ISIZE-1
C
C	USE 2048 COORDINATES (UNLESS ISIZE<2048)
C
	NVALS=MIN(ISIZE,2048)
	DO I=0,NVALS-1
		J=(I*ISIZEM1)/(NVALS-1)
		XVALS(I)=J
		IF (LLOG) THEN
			YVALS(I)=MAX(INPUT(J),0.0)+1
		ELSE
			YVALS(I)=INPUT(J)
		ENDIF
	ENDDO
C
C	NOW USE SIMPLEPLOT TO PLOT THE ARRAY
C
	IF (LLOG) THEN
		NVALS2=-NVALS
	ELSE
		NVALS2=NVALS
	ENDIF
	CALL JBAXES(XVALS,NVALS,18.0,'BINS',4,
     +		   YVALS,NVALS2,15.0,'COUNTS',6)
	CALL DRAWCV(XVALS,YVALS,NVALS)
C
C	SIMPLEPLOT WILL HAVE CALLED T4010 AND WILL HAVE ALSO
C	CALLED WINDOL SO THAT USER COORDS ARE DEVICE COORDS
C
C	DEFINE THE FOLLOWING CURSOR KEYS:-
C		L	LEFT LIMIT
C		R	RIGHT LIMIT
C
C	AND INFORM USER OF THE ONLY HONOURABLE COURSE OF ACTION
C
	ICURSE=0
	LIMS(1)=32767
	LIMS(2)=-32768
	CALL CURDEF('LR*.')
	CALL WRUSER('USE THE CURSOR TO DEFINE LEFT AND RIGHT '//
     +	'LIMITS',STATUS)
	CALL WRUSER('L	LEFT LIMIT',STATUS)
	CALL WRUSER('R	RIGHT LIMIT',STATUS)
C
C	READ CURSOR UNTIL L AND R ARE DEFINED OK
C
	DO WHILE (LIMS(1).GE.LIMS(2))
		CALL CURSE(ICURSE,X,Y)
		IF (ICURSE.LE.2) THEN
			LIMS(ICURSE)=X+0.5
			WRITE (VAL,'(I4)') LIMS(ICURSE)
			CALL WRUSER(LR(ICURSE)//' VALUE IS'//
     +			VAL,STATUS)
		ELSE
			CALL WRUSER('ILLEGAL KEY',STATUS)
		ENDIF
	ENDDO
	CALL ENDPLT
	RETURN
	END
