      SUBROUTINE LOAD
C
C     REGISTRATION POINTS ARE LOADED INTO A STARLINK FILE
C              FORMAT IS X,Y,WT FOR INPUT AND OUTPUT IMAGE
C
      IMPLICIT INTEGER (A-Z)
      INCLUDE 'INTERIM(ERRPAR)'
      INCLUDE 'INTERIM(FMTPAR)'
      CHARACTER KEY*1
	INTEGER POINTS(3), IDIM(2),ODIM(2)
	DATA POINTS/3,2,0/
      DATA KEY/'K'/
C
C     ASK FOR METHOD OF LOADING POINTS
C         POSSIBILITIES ARE: (1) FROM KEYBOARD
C                            (2) BY CURSOR FROM DISPLAYED IMAGE
C                            (3) FROM 2 FILES
C
100   CALL RDKEYC('KEYING',.TRUE.,1,KEY,AVAL,STATUS)
      CALL CNPAR('KEYING',STATUS)
      IF(KEY.EQ.'K') GO TO 200
      IF(KEY.EQ.'F') GO TO 300
      IF(KEY.EQ.'C') GO TO 400
      GO TO 100
C
C    READ X,Y AND WEIGHT FROM KEYBOARD
C
200   CALL RDKEYI('NUMBER',.FALSE.,1,NUM,AVAL,STATUS)
      IF(NUM.LT.3) THEN
      CALL CNPAR('NUMBER',STATUS)
      GO TO 200
      ENDIF
      CALL CNPAR('NUMBER',STATUS)
C
C     OPEN FILE FOR REGISTRATION POINTS
C
	POINT = NUM
	POINTS(3) = NUM
	CALL WRIMAG('RFILE',FMT_R,POINTS,3,IPOINT,STATUS)
      IF(STATUS.NE.ERR_NORMAL) THEN
      CALL WRERR('RERRF')
      CALL FRDATA(' ',STATUS)
      RETURN
      ENDIF
C
C
C     LOAD REGISTRATION POINTS INTO THE FILE
C
      CALL LOADR(%VAL(IPOINT),NUM)
      CALL FRDATA('RFILE',STATUS)
      RETURN
C
C      LOAD REGISTRATION POINTS FROM 2 FILES
C
300   CALL RDIMAG('IN',FMT_R,2,IDIM,AVAL,INPT,STATUS)
      IF(STATUS.NE.ERR_NORMAL) THEN
      CALL WRERR('INERR')
      CALL FRDATA('IN',STATUS)
      CALL CNPAR('IN',STATUS)
      RETURN
      ENDIF
      CALL RDIMAG('OUT',FMT_R,2,ODIM,AVAL,OUTPT,STATUS)
      IF(STATUS.NE.ERR_NORMAL) THEN
      CALL WRERR('OUTERR')
      CALL FRDATA(' ',STATUS)
      CALL CNPAR('IN',STATUS)
      CALL CNPAR('OUT',STATUS)
      RETURN
      ENDIF
      NUM = IDIM(1)
      CALL RDKEYI('NUMBER',.TRUE.,1,NUM,AVAL,STATUS)
      POINTS(3) = NUM
      CALL WRIMAG('RFILE',FMT_R,POINTS,3,IPOINT,STATUS)
      CALL LOADF(%VAL(INPT),%VAL(OUTPT),%VAL(IPOINT),
     *    IDIM(1),IDIM(2),ODIM(1),ODIM(2),NUM)
      CALL FRDATA(' ',STATUS)
      CALL CNPAR('IN',STATUS)
      CALL CNPAR('OUT',STATUS)
      CALL CNPAR('RFILE',STATUS)
      RETURN
C
C      LOAD REGISTRATION POINTS FROM DISPLAYED IMAGE
C
400   CALL WRUSER('CURSOR NOT AVAILABLE YET',STATUS)
      RETURN
      END
