      LOGICAL FUNCTION NUMBER(CHAR)
C
C      TESTS WHETHER THE CHARACTER IS A NUMBER
C      WHERE THIS INCLUDES DECIMAL POINTS(.) & SIGNS(+-)
C      INPUT PARAMETERS:
C        CHAR   -  CHARACTER*1 VARIABLE HOLDING THE CHARACTER
C
      CHARACTER*1 CHAR
      N = ICHAR(CHAR)
      NUMBER = N.GE.ICHAR('0').AND.N.LE.ICHAR('9').OR.CHAR.
     1 EQ.'.'.OR.CHAR.EQ.'+'.OR.CHAR.EQ.'-'
      RETURN
      END
 
