      SUBROUTINE PP(PRFL,N,TINT,C,W)
*
*  EVALUATE 1-D STAR PROFILE
*
*  GIVEN:
*     PRFL        1-D ARRAY CONTAINING STAR PROFILE
*     N           SIZE OF ARRAY
*
*  RETURNED:
*     TINT        TOTAL INTENSITY (ABOVE BACKGROUND)
*     C           CENTRE
*     W           FWHM
*

      INTEGER N
      REAL PRFL(N),TINT,C,W

      DOUBLE PRECISION SZ,SZP,SZP2


*  BASELINE PARAMETERS (STRAIGHT LINE THROUGH ENDPOINTS)
      Z0=PRFL(1)
      SLOPE=(PRFL(N)-Z0)/REAL(N)

*  PERFORM SUMMATIONS
      SZ=0D0
      SZP=0D0
      SZP2=0D0
      DO I=2,N-1
         P=REAL(I-1)
         Z=PRFL(I)-(Z0+SLOPE*P)
         SZ=SZ+DBLE(Z)
         ZP=Z*P
         SZP=SZP+DBLE(ZP)
         SZP2=SZP2+DBLE(ZP*P)
      END DO

*  FUDGE TOTAL INTENSITY IF VERY SMALL
      TINT=REAL(SZ)
      IF (ABS(TINT).LT.1E-10) SZ=1D0

*  DETERMINE CENTRE OF GRAVITY AND FWHM (ASSUMING GAUSSIAN)
      C=REAL(SZP/SZ)
      W=2.35482*SQRT(MAX(REAL((SZP2-SZP*SZP/SZ)/SZ),0.0))

      END
