      SUBROUTINE RDDEC(CHARS,J,K,DEC,IERR)
C
C      READ IN A DECLINATION
C      INPUT PARAMETERS:-
C      CHARS - STRING HOLDING STRING REPRESENTING DECLINATION
C      J,K   - 1ST & LAST CHARACTERS IN THE STRING DELIMITING
C              THE DECLINATION CHARACTERS
C      OUTPUT PARAMETERS:-
C      DEC   - DOUBLE PRECISION VALUE OF THE DECLINATION
C      IERR  - VALUE DENOTING ERROR.AS RETURNED FROM READPOS
C
      DOUBLE PRECISION TWOPI,HALFPI,RDSA,RDST,RDDG
      COMMON/CONVF/TWOPI,HALFPI,RDSA,RDST,RDDG
      CHARACTER*40 STRING
      CHARACTER*(*) CHARS
      DOUBLE PRECISION DEC,ANGLE
      STRING=CHARS(J:K)
      CALL READPOS(STRING,ANGLE,IERR)
      IF (IERR.EQ.1) THEN
        PRINT *,' Format Error'
        RETURN
      ENDIF
      IF (IERR.EQ.2) THEN
        WRITE (6,*) ' Error - Dec is in Degrees,Mins and Secs'
        RETURN
      ENDIF
      DEC  = ANGLE * 3.6D3 *RDSA
      IF (ABS(DEC).GT.HALFPI) THEN
        WRITE (6,*) ' Error - Dec must be no more than 90 Degrees'
        IERR = 3
        RETURN
      ENDIF
      RETURN
      END
 
 
