      SUBROUTINE READPOS(STRING,ANGLE,IERR)
C
C      READPOS PICKS OUT UP TO 3 COMPONENTS
C      IN FREE FORMAT. IT RETURNS A VALUE
C      OF THE NUMBER WHICH MAY BE IN
C
C      THE CHARACTER STRING MAY HAVE UP TO N NUMBERS
C      IN CHARACTER SUBSTRINGS. THEY ARE DELIMITED
C      BY ANY NON-NUMERIC CHARACTER
C      INPUT PARAMETERS:
C       STRING  -  A CHARACTER VARIABLE CONTAINING
C                  THE NUMERIC SUBSTRINGS
C      OUTPUT PARAMETERS:
C       ANGLE   -  THE EVALUATED ANGLE IN DEGS. OR HOURS
C       IERR    -  RETURNS VALUE 1 IF THERE IS NO
C                  NUMBER IN THE INPUT STRING
C
 
      DOUBLE PRECISION ANGLE,PART
      LOGICAL NEGNUM,NUMBER
      DIMENSION PART(3)
      CHARACTER*(*) STRING
      CHARACTER*1 CHAR
      DO 50 K=1,3
      PART(K)=0.0D0
50    CONTINUE
      LENGTH=LEN(STRING)
      NCHAR = 0
      IERR = 0
      NEGNUM = INDEX(STRING,'-').NE.0
      DO 200 K=1,3
100   NCHAR = NCHAR+1
C
C     LOOK FOR A NUMERIC CHARACTER
C
      IF (NCHAR.GE.LENGTH) THEN
        IF (K.EQ.1) THEN    !ERROR,NO NUMBERS FOUND
          GOTO 700
            ELSE
          GOTO 800                !END OF STRING,OK
        ENDIF
      ENDIF
      CHAR = STRING(NCHAR:NCHAR)
      IF (.NOT.NUMBER(CHAR)) GOTO 100
C
C      FOUND START OF A NUMBER
C
      N1 = NCHAR
110   NCHAR= NCHAR+1
      IF (NCHAR.GE.LENGTH) GOTO 800
      CHAR = STRING(NCHAR:NCHAR)
      IF (NUMBER(CHAR)) GOTO 110
C
C     END OF NUMERIC FIELD FOUND
C     EVALUATE THE SUBSTRING
C
      N2 = NCHAR -1
      PART(K) = VAL(STRING,N1,N2,IFAIL)
      IERR=IFAIL
      IF (K.GT.1.AND.PART(K).GT.6.0D1) IERR = 2
200   CONTINUE
C
800   ANGLE = PART(1) + PART(2)/6.0D1 + PART(3)/3.6D3
      IF (NEGNUM) ANGLE = -ANGLE
      GOTO 850
C
C      NO NUMBERS FOUND,ERROR
C
700   IERR = 1
850   RETURN
      END
 
