      SUBROUTINE RECT(DATA,NX,NY,IXSIZE,IYSIZE,IX,IY)
C
C+     THIS ROUTINE REWRITES PART OF AN IMAGE ON THE ARGS
C
C      THE FIRST TIME IT IS CALLED IT FILLS AN ARRAY (49*49) WITH
C      DATA AND ADDS A RECTANGULAR FRAME ON THE SAME CENTRE ,
C      OF SIZE IXSIZE BY IYSIZE ,, AND THE WRITES IT TO THE ARGS
C
C      SUBSEQUENT CALLS REWRITE THE ORIGINAL DATA AT THE PREVIOUS
C      POSITION AND WRITE A NEW ONE AT THE NEW POSITION.
C      THIS SHOULD ERASE THE "CURSOR"
C
      INTEGER*2 DATA(NX,NY),PART(49,49)
      SAVE IFLAG
      DATA IFLAG/0/
C
C      IFLAG IS USED TO INDICATE IF THIS IS THE FIRST CALL
C
C
C      IF IT IS NOT THE FIRST TIME ERASE THE OLD RECTANGLE
C      AT POSITION IXO,IYO
C
      IF (IFLAG.EQ.999) THEN
         ILIM1=IXO-24
         ILIM2=IXO+24
         JLIM1=IYO-24
         JLIM2=IYO+24
         JO=1
         DO 200 J=JLIM1,JLIM2
            IO=1
            DO 100 I=ILIM1,ILIM2
               IF (I.GE.1.AND.I.LE.NX.AND.J.GE.1.AND.J.LE.NY) THEN
                  PART(IO,JO)=DATA(I,J)
               ELSE
                  PART(IO,JO)=0
               END IF
               IO=IO+1
  100       CONTINUE
            JO=JO+1
  200    CONTINUE
         CALL AIM(PART,49,49,IXO-25,IYO-25,16,2401,ISTAT)
      ELSE
         IFLAG=999
      END IF
C
C      NOW SET OLD POSITION TO NEW POSITION
C
      IXO=IX
      IYO=IY
C
C      NOW PREPARE THE NEW BOX
C
      ILIM1=IX-24
      ILIM2=IX+24
      JLIM1=IY-24
      JLIM2=IY+24
      JO=1
      DO 400 J=JLIM1,JLIM2
         IO=1
         DO 300 I=ILIM1,ILIM2
            IF (I.GE.1.AND.I.LE.NX.AND.J.GE.1.AND.J.LE.NY) THEN
               PART(IO,JO)=DATA(I,J)
            ELSE
               PART(IO,JO)=0
            END IF
            IO=IO+1
  300    CONTINUE
         JO=JO+1
  400 CONTINUE
C
C      NOW CREATE THE RECTANGLE
C
      IHW=(IXSIZE-1)/2
      JHW=(IYSIZE-1)/2
      DO 500 I=25-IHW,25+IHW
         PART(I,25-JHW)=255
         PART(I,25+JHW)=255
  500 CONTINUE
      DO 600 J=25-JHW,25+JHW
         PART(25-IHW,J)=255
         PART(25+IHW,J)=255
  600 CONTINUE
C
C      NOW WRITE THE NEW BOX
C
      CALL AIM(PART,49,49,IX-25,IY-25,16,2401,ISTAT)
      RETURN
      END
