        SUBROUTINE ROTATE(COEFF,DEGREE,ORIGIN)
C
C      INSERTS ROTATION COEFFICIENTS INTO IMAGE FILE
C
       REAL*8 COEFF(2,8)
       REAL*4 ORIGIN(2)
       DO I=1,2
       DO J=1,8
       COEFF(I,J)=0.0D0
       ENDDO
       ENDDO
C
       RADS=DEGREE*3.141592654/180.0
      COEFF(1,1)=(1.0-COS(RADS)) * ORIGIN(1) + SIN(RADS)*ORIGIN(2)
      COEFF(1,2)=COS(RADS)-1.0
      COEFF(1,3)=-SIN(RADS)
      COEFF(2,1)=(1.0-COS(RADS))*ORIGIN(2) - SIN(RADS)*ORIGIN(1)
      COEFF(2,2)=SIN(RADS)
      COEFF(2,3)=COS(RADS)-1.0
       RETURN
       END
