      SUBROUTINE ROTA
C
C     CALCULATES COEFFICIENTS FOR A ROTATION OF N DEGREES
C     ROUND AN ORIGIN OX OY
C
      IMPLICIT INTEGER (A-Z)
        INCLUDE 'INTERIM(ERRPAR)'
	INCLUDE 'INTERIM(FMTPAR)'
C
      REAL DEGREE,ORIGIN(2)
      INTEGER LDIM(2)
      CHARACTER*1 CORDER
      DATA LDIM/2,8/
C
C     READ ROTATION IN DEGREES(CLOCKWISE)
C
      CALL CNPAR('degrees',STATUS)
      CALL RDKEYR('degrees',.FALSE.,1,DEGREE,I,STATUS)
      IF (STATUS.NE.ERR_NORMAL) THEN
      CALL WRERR('ROTERR')
      RETURN
      ENDIF
100   CALL CNPAR('centre',STATUS)
      CALL RDKEYR('centre',.TRUE.,2,ORIGIN,AVAL,STATUS)
      IF (STATUS.NE.ERR_NORMAL.AND.STATUS.NE.ERR_PARNUL) THEN
      CALL WRERR('ORIERR')
      RETURN
      ENDIF
      IF (AVAL.NE.2.AND.AVAL.NE.0) THEN
      CALL WRUSER('ORIGIN WRONG PLEASE REPEAT')
      GO TO 100
      ENDIF
C
C	CREATE COEFFICIENT FILE
C
	CALL WRIMAG('coefts',FMT_DP,LDIM,2,IPOINT,STATUS)
	  IF(STATUS.NE.ERR_NORMAL) THEN
	    CALL WRERR('ERRIMAG')
	    RETURN
	  ENDIF
        WRITE(CORDER,900)
900     FORMAT('3')
        CALL WRDSCR('coefts','ORDER',CORDER,1,STATUS)
       CALL ROTATE (%VAL(IPOINT),DEGREE,ORIGIN)
        CALL FRDATA(' ',STATUS)
        CALL CNPAR('coefts',STATUS)
        RETURN
        END
