      SUBROUTINE SELECT
      INCLUDE 'INTERIM(ERRPAR)'
      CHARACTER TERM*1,NUMB*4
      DATA TERM/'N'/
      CALL WRUSER('SECOND TERMINAL FOR GRAPHICS OUTPUT',ISTAT)
      CALL RDKEYC('TERM',.TRUE.,1,TERM,IVAL,ISTAT)
      IF(ISTAT.NE.ERR_PARNUL.AND.ISTAT.NE.ERR_NORMAL) THEN
      CALL WRERR('ERRTERM')
      STOP
      ENDIF
      IF(TERM.EQ.'Y') THEN
      CALL WRUSER('INPUT TERMINAL NAME E.G. TTA1',ISTAT)
      CALL RDKEYC('NUMBER',.FALSE.,1,NUMB,IVAL,ISTAT)
      IF(ISTAT.NE.ERR_NORMAL) THEN
      CALL WRERR('ERRNUM')
      STOP
      ENDIF
      CALL SELSTA(NUMB)
      ENDIF
      RETURN
      END
