      DOUBLE PRECISION FUNCTION VAL(STRING,J,K,IFAIL)
C
C      EVALUATES A NUMERIC SUBSTRING OF A CHARACTER STRING
C      AS AN UNSIGNED STRING I.E. IGNORE NEGATIVE SIGN
C      VALUE IS RETURNED IN DOUBLE PRECISION
C
C      INPUT PARAMETERS:
C         STRING  - CHARACTER VARIABLE CONTAINING THE SUBSTRING
C         J,K     - CHARACTER POSITIONS DEFINING THE NUMERIC SUBSTRING
C         OUTPUT PARAMETER:-
C         IFAIL    =1 IF A NON=NUMERIC STRING
C
      INTEGER J,K
      CHARACTER*(*) STRING
      CHARACTER*8 FORMAT
      IFAIL=0
      NPOINT =  INDEX(STRING(J:K),'.')
      IF (NPOINT.GT.0) NPOINT = K - J + 1 - NPOINT
      NFIG=K - J + 1
      WRITE (FORMAT,900) NFIG,NPOINT
900   FORMAT('(D',I2,'.',I2,')')
      READ (STRING(J:K),FORMAT,ERR=300) VAL
      VAL = ABS(VAL)
      RETURN
300   CALL ERRSNS(IERR)
      IF (IERR.EQ.64) THEN
        IFAIL=1
        RETURN
      ELSE
        WRITE (6,*) 'UNEXPECTED CONVERSION ERROR'
        IFAIL=1
      ENDIF
      END
 
