      SUBROUTINE ARGPLOT(SPEC,NQUAD)
C+
C   ARGPLOT
C
C     PLOT 1-D ARRAY IN DESIRED QUADRANT OF ARGS
C
C	GIVEN:		(ARGUMENTS)
C	NQUAD, SPEC		
C
C
C       J.A.COOKE/UOE/1981
C	B.D KELLY/ROE/1981
C-
      REAL SPEC(128),POS(128)
C
C     FIND WHICH QUADRANT
C
      XR=0.0
      YR=0.0
      IF(NQUAD.EQ.1) THEN
        XR=0.5
        YR=0.5
      ELSE IF(NQUAD.EQ.2) THEN
        XR=0.0
        YR=0.5
      ELSE IF(NQUAD.EQ.4) THEN
        XR=0.5
        YR=0.0
      ENDIF
      IXR=0
      IYR=0
      IF(XR.GT.0.1) IXR=256
      IF(YR.GT.0.1) IYR=256
      CALL ARGSET(0)
      CALL VUPORT(XR,XR+0.5,YR,YR+0.5)
C
C   PLOT
C
      DO I=1,128
         POS(I)=REAL(I)
      ENDDO
      CALL TYPLO1(3,0)
      CALL WINDO(POS,SPEC,128,128,XMIN,XMAX,YMIN,YMAX,.FALSE.)
      CALL WINDOL(1.0,128.0,YMIN,YMAX)
      CALL QLOT(POS,SPEC,128,128)
      CALL STOPLOT

      END
