	SUBROUTINE CRPRFL (MSIZE,PARMFIL)
C+
C	 Interim Subroutine to create a parameter file.
C
C	 Given;
C	 MSIZE - Size of array.
C
C	 Returned;
C	 PARMFIL - Array of values.
C
C	 A C Davenhall. /ROE/			10.12.81.
C-
	INTEGER MSIZE
	REAL PARMFIL(MSIZE)
	REAL LOGMIN
	INTEGER ISTAT
	CHARACTER REPLY*15
	CALL INPLT (ICST,IRST,PLTSCL,ISTAT)
	PARMFIL(1)=FLOAT(ICST)
	PARMFIL(2)=FLOAT(IRST)
	PARMFIL(3)=PLTSCL
	CALL INEQPR (LOGMIN,DELOGI,NLEVEL,ISTAT)
	PARMFIL(5)=LOGMIN
	PARMFIL(6)=DELOGI
	PARMFIL(7)=FLOAT(NLEVEL)
	ISTAT=0
	CALL READR ('SKY',' Enter Sky Brightness;',21.55,
     :	    18.0,27.0,SKYCON,ISTAT)
	PARMFIL(4)=SKYCON
	ISTAT=0
	CALL MULREP (
     : ' Type of extrapolation correction for total magnitude?',
     : 'DEVAUC,SPIRAL,ELLIPTICAL$',REPLY,ISTAT)
	IF (REPLY.EQ.'DEVAUC') PARMFIL(8)=1.0E0
	IF (REPLY.EQ.'SPIRAL') PARMFIL(8)=3.0E0
	IF (REPLY.EQ.'ELLIPTICAL') PARMFIL(8)=2.0E0
	PARMFIL(9)=0.0E0	! CORR
	PARMFIL(10)=1.0E0	! DISP - PRINT/DELETE.
	END
