      SUBROUTINE HISTDEF(IXEXT,IYEXT,ARRAY,RMIN,RMAX)
*+
*   HISTDEF
*
*   RETURNS MAXIMUM AND MINIMUM PIXEL VALUES IN A 2-D ARRAY.
*
*   GIVEN         (ARGUMENTS)
*   IXEXT    I     X-DIMENSION OF DATA ARRAY
*   IYEXT    I     Y-DIMENSION OF DATA ARRAY
*   ARRAY    RA    DATA ARRAY
*
*   RETURNED      (ARGUMENTS)
*   RMIN     R     MINIMUM VALUE IN ARRAY
*   RMAX     R     MAXIMUM VALUE IN ARRAY
*
*-

      INTEGER IXEXT,IYEXT
      REAL ARRAY(IXEXT,IYEXT),RMIN,RMAX

      RMAX=ARRAY(1,1)
      RMIN=RMAX

      DO J=1,IYEXT
         DO I=1,IXEXT
            RMAX=MAX(RMAX,ARRAY(I,J))
            RMIN=MIN(RMIN,ARRAY(I,J))
         ENDDO
      ENDDO

      END
