C
C	SUBROUTINE TO INTEGRATE AN ARRAY OF POINTS BY 
C	SIMPSON'S RULE.
C
C	NOTE:- **MUST** BE GIVEN AN ODD NUMBER OF POINTS.
C
	SUBROUTINE SIMP (Y,H,NPTS,M,RESULT)
	DIMENSION Y(M)
	DATA ZERO,THREE,FOUR,IZ,IONE,I2/0.0E0,3.0E0,4.0E0,0,1,2/
	RESULT=ZERO
	MPTS=NPTS-I2
	DO 1 I=1,MPTS,2
  	RESULT=RESULT+(Y(I)+(FOUR*Y(I+IONE))+Y(I+I2))
 1	CONTINUE
	RESULT=RESULT*H/THREE
	RETURN
	END
