      SUBROUTINE WRHELP
      CALL WRUSER(' ',I)
      CALL WRUSER('Program to edit a table of real numbers by',I)
      CALL WRUSER('operations on complete rows (not possible',I)
      CALL WRUSER('to modify a smaller unit than a row).',I)
      CALL WRUSER('Commands may prompt for row number',I)
      CALL WRUSER(' ',I)
      CALL WRUSER('C  n   CHANGE row n by typing in new row',I)
      CALL WRUSER('D  n   DELETE row n',I)
      CALL WRUSER('I  n   INSERT row n by typing in new row',I)
      CALL WRUSER('L  s,f LIST   rows s to f on terminal',I)
      CALL WRUSER('P      PRINT  whole table on terminal',I)
      CALL WRUSER('H      HELP   show this help info on terminal',I)
      CALL WRUSER('Q      QUIT   the program',I)
      CALL WRUSER(' ',I)
      CALL WRUSER('The rows are renumbered immediately after D,I',I)
      CALL WRUSER('as a row will have been taken away/added.',I)
      CALL WRUSER('Do not type row number hen entering a row',I)
      CALL WRUSER(' ',I)
      END
