
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C      **************
C      *            *
C      * S/R DISPL  *
C      *            *
C      **************
C
C



      SUBROUTINE DISPL(IPIC,KX,KY,IXC,IYC,TRIM,LLOG,VLO,VHI,
     +                 KXR,KYR,KCOMP)
C
C
C
      INTEGER*2 IPIC(KX,KY),IDUMMY
      LOGICAL TRIM,LLOG
      CHARACTER VALUE*80
      INTEGER KXR(2),KYR(2)
      CHARACTER TEXTAR*80
C
C
C
      CALL ASP_SWSP(500,8)
      CALL SRPXI2(IPIC,KX,KX,KY,IXC-KX/2,IYC-KY/2,
     +            16,.FALSE.,IDUMMY,1)
      CALL ASP_RWSP
      CALL ARGS_NUMIM(IDMAX)
      IF (IDMAX.GE.1) THEN
         CALL ARGS_RDPAR('DISPZOOM',1,VALUE,NVALS,JSTAT)
         CALL ASP_DZTOI('ZXC',VALUE,IZXC,JSTAT)
         CALL ASP_DZTOI('ZYC',VALUE,IZYC,JSTAT)
         CALL ASP_DZTOI('ZXF',VALUE,IXF,JSTAT)
         CALL ASP_DZTOI('ZYF',VALUE,IYF,JSTAT)
         CALL ARGS_WRPAR('DISPZOOM',VALUE,1,JSTAT)
      ELSE
         IZXC=256
         IZYC=256
         IXF=1
         IYF=1
      ENDIF
      CALL ARGS_WRIM (IXC,IYC,KX,KY,KX,KY,JSTAT)
      IF (JSTAT.NE.0) THEN
         CALL WRUSER('COULDN''T UPDATE ARGS DATABASE',JSTAT)
      ELSE
         CALL ARGS_RDPAR ('DISPZOOM',1,VALUE,NVALS,JSTAT)
         CALL ASP_LTODZ ('TRIM',TRIM,VALUE,JSTAT)
         CALL ASP_LTODZ ('LOG',LLOG,VALUE,JSTAT)
         CALL ASP_FTODZ ('PVLO',VLO,VALUE,JSTAT)
         CALL ASP_FTODZ ('PVHI',VHI,VALUE,JSTAT)
         CALL ASP_ITODZ ('ZXC',IZXC,VALUE,JSTAT)
         CALL ASP_ITODZ ('ZYC',IZYC,VALUE,JSTAT)
         CALL ASP_ITODZ ('ZXF',IXF,VALUE,JSTAT)
         CALL ASP_ITODZ ('ZYF',IYF,VALUE,JSTAT)
         CALL ARGS_WRPAR ('DISPZOOM',VALUE,1,JSTAT)
         WRITE(TEXTAR,903)KXR(1),KXR(2),KYR(1),KYR(2),KCOMP
  903    FORMAT(5I10)
         CALL ARGS_WRPAR('COMPRE',TEXTAR,1,ISTAT)
      ENDIF
C
C
C
      END



