C COMMON BLOCK TO COMMUNICATE BETWEEN THE GTHELP ROUTINE
C AND AN OUTPUT ROUTINE WHICH CONTROLS THE FORMATTING OF
C HELP INFORMATION ON THE USER'S SCREEN
C
C THE NUMBER OF NON-BLANK LINES OUTPUT SO FAR (INITIALLY SET NEGATIVE
C TO SUPRESS FIRST FEW LINES)
C
      INTEGER NLOUT
C
C FLAG TO INDICATE IF INITIAL BLANKS ON LINES ARE TRIMMED OFF
C
      LOGICAL TRIM
C
C SUCCESS STATUS: HELP FOUND OR NOT
C
      LOGICAL CANHLP
      COMMON /HLPBL1/NLOUT,TRIM,CANHLP
