      SUBROUTINE ROECNTRLC(I)
      EXTERNAL ASTCNC
      INTEGER*4 I,VECT2(3)
      INTEGER*2 TTCHAN,VECT1(2)
      CHARACTER*63 NAME
      LOGICAL*2 CTRLC_
      COMMON/CTCAST/CTRLC_
      EQUIVALENCE (VECT1(1),VECT2(1))
      DATA VECT1(1)/3/,VECT1(2)/15/,VECT2(2)/44/,VECT2(3)/0/
      DATA TTCHAN/49/
C
C  CHECK FOR CONTROL C AST ENABLE
C
      IF(IABS(I) .EQ. 1) THEN

	J=SYS$TRNLOG('TT',,NAME,,,)
C
C  CHECK FOR ERROR IN LOGICAL NAME TRANSLATION
C
	IF(.NOT. J .AND. (J .NE. SS$_NORMAL)) THEN

		K=SYS$PUTMSG(VECT2,,'TRNLOG')
		K=SYS$EXIT(%VAL(J))

	END IF

	J=SYS$ASSIGN(NAME,TTCHAN,,)
C
C  CHECK FOR ERROR IN CHANNEL ASSIGNMENT
C
	IF(.NOT. J .AND. (J .NE. SS$_NORMAL)) THEN

		K=SYS$PUTMSG(VECT2,,'ASSIGN')
		K=SYS$EXIT(%VAL(J))

	END IF

	J=SYS$QIOW(,%VAL(TTCHAN),%VAL(291),,,,ASTCNC,,,,,)
C
C  CHECK FOR ENABLE AST ERROR
C
	IF(.NOT. J .AND. (J .NE. SS$_NORMAL)) THEN

		K=SYS$PUTMSG(VECT2,,'ASTEN')
		K=SYS$EXIT(%VAL(J))

	END IF

	CTRLC_ = .FALSE.
	RETURN
	END IF
C
C  CHECK FOR AST DISABLE
C
      IF(I .EQ. 0) THEN

	J=SYS$QIOW(,%VAL(TTCHAN),%VAL(291),,,,,,,,,)
C
C  CHECK FOR AST DISABLE ERRORS
C
	IF(.NOT. J .AND. (J .NE. SS$_NORMAL)) THEN

		K=SYS$PUTMSG(VECT2,,'ASTDIS')
		K=SYS$EXIT(%VAL(J))

	END IF

	CTRLC_ = .FALSE.
	RETURN

      END IF

      K=SYS$PUTMSG(VECT2,,'ASTPRM')
      K=SYS$EXIT(%VAL(1))
      RETURN
      END
