      SUBROUTINE ARCEMA(KX,KY,KXF,KYF,KW)
 
 
 
      CHARACTER VALUE*80
 
 
      INCLUDE 'INTERIM(ERRPAR)'
      INCLUDE 'INTERIM(FMTPAR)'
 
 
 
*  IF WANTED, USE PRESENT MAGNIFICATION
 
      IF (KW.EQ.0) THEN
         CALL ARGS_RDPAR('DISPZOOM',1,VALUE,NVALS,ISTAT)
         CALL ASP_DZTOI('ZXF',VALUE,KXF,ISTAT)
         CALL ASP_DZTOI('ZYF',VALUE,KYF,ISTAT)
      ENDIF
 
*  DO THE ZOOM
 
      CALL IZOOM(KX,KY,KXF,KYF)
      CALL ARGS_RDPAR('DISPZOOM',1,VALUE,NVALS,JSTAT)
      CALL ASP_ITODZ('ZXC',KX,VALUE,JSTAT)
      CALL ASP_ITODZ('ZYC',KY,VALUE,JSTAT)
      CALL ASP_ITODZ('ZXF',KXF,VALUE,JSTAT)
      CALL ASP_ITODZ('ZYF',KYF,VALUE,JSTAT)
      CALL ARGS_WRPAR('DISPZOOM',VALUE,1,JSTAT)
 
 
 
      END
 
