      SUBROUTINE ARGS_OVOPN(N,COL)
*
*+ PERFORM ALL INITIALISATION TO ALLOW USE OF BIT PLANE 'N'
* FOR OVERLAYS. OVERLAYS WILL BE IN COLOUR 'COL' (SEE 'ARGS_DECOL')
 
      INTEGER N,MASKN
      CHARACTER COL
 
* RESET VSR
      CALL ARGS_VSRRST
 
* DISABLE OVERLAYS TEMPORARILY
      CALL ARGS_OVCG('0')
 
* ENABLE PLANE 'N' AND SET ZDI
      MASKN = IAND(N,'000F'X)
      CALL ARGS_FLUSH(9)
      CALL ARGS_S1('ZWEI',ISHFT('0001'X,MASKN))
      CALL ARGS_S1('ZDI1',ISHFT('0001'X,MASKN))
 
* ENABLE OVERLAYS FOR BIT PLANE 'N'
      CALL ARGS_OVCG('W')
      CALL ARGS_OVC(ISHFT('0001'X,IAND(N,'007'X)),COL)
 
      END
 
 
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C      **************
C      *            *
C      * S/R ARCEMA *
C      *            *
C      **************
C
C  ORIG PROGRAM PTW MOD 28/7/81 WFL TO ACCESS ARGS DATABASE
C  MOD BY AJP TO S/R ARCEMA 82 SEP
C
C ------------------------------------------------------
 
 
 
