      SUBROUTINE ARGS_FPRI2(BUFF,N,X1,Y1,NX,NY)
C
C READS PACKED PIXEL ARRAY FROM ARGS.
C ARGUMENTS
C   BUFF   (ARRAY) ON OUTPUT CONTAINS PACKED DATA (INTEGER*2)
C   N      (ENTRY) NUMBER OF INTEGER*2 ELEMENTS IN BUFF
C   X1,Y1  (ENTRY) BOTTOM LEFT OF PIXEL IMAGE.
C   NX,NY  (ENTRY) NUMBER OF PIXELS TO BE OCCUPIED IN X & Y RESP.
C
      INTEGER*2 BUFF(N),IBUFF(32771)
      INTEGER X1,Y1,NX,NY
      INTEGER NW,AW,PPAW,NAME
      INTEGER*2 CHECK,IRDINS(10)
C
      INTEGER*2 IJUNK
      LOGICAL LPRT,LARGSD,LARGSS,INITD
      COMMON /CARGS1/IJUNK(520),L1,L2,L3,LPRT,LARGSD,LARGSS,
     1 CHAN,INITD,L4
      DATA NW/1/
      DATA NAME/3HFPR/
C
C   CHECK ARRAY EXTREMITIES
      CHECK=BUFF(1)
      CHECK=BUFF(N)
C   CHECK NUMBER OF WORDS
      IF( N*NW.GT.32767 ) CALL ARGS_ITF(12,.TRUE.,N,N,Z)
C   (P)IXELS (P)ER (A)RGS (W)ORD
      PPAW=1
C   NEED EXACT NUMBER OF ARGS DATA WORDS OR FEWER.
      AW=MIN( N*NW, (NX*NY+PPAW-1)/PPAW)
C
C   MOVE PEN, OUTPUT ARGS ORDER & THEN READ THE IMAGE.
C
      CALL ARGS_S1(3HXMA,X1)
      CALL ARGS_S1(3HYMA,Y1)
C
C     OPCODE FOR READING ARGS = '6B04'
C
      IRDINS(5)='6B04'X
      IRDINS(6)=X1
      IRDINS(7)=Y1
      IRDINS(8)=NX
      IRDINS(9)=NY
      IRDINS(10)=AW
C
C     ARGS_IDCALLRD SENDS 'IRDINS' TO THE ARGS AND RECEIVES
C        THE REPLY IN IBUFF.  THERE ARE 4 HEADER WORDS IN THE
C        BEGINNING OF EACH BUFFER WHICH MUST BE IGNORRED.
C
      CALL ARGS_IDCALLRD(1,CHAN,IRDINS,10,IBUFF,AW+4,NOK)
C
      DO I=1,AW
        BUFF(I)=IBUFF(I+4)
      END DO
      END
