      SUBROUTINE ARGSROW(ARRAY,ICOL,IROW,I1,I2,J,
     1         TRIM,LLOG,VLO,VHI,IXOR,IYOR)
      REAL ARRAY(ICOL,IROW)
	LOGICAL TRIM,LLOG
      INCLUDE 'INTERIM(FMTPAR)'
      ISIZE=I2-I1+1
      CALL GETDYN('QROW',FMT_R,ISIZE,IPNT,ISTATUS)
      IF (ISTATUS .NE. 0)THEN
        PRINT *,'FAILED TO GET WORKSPACE IN ARGSROW'
        CALL FRDATA('QROW',ISTATUS)
        RETURN
      END IF
      CALL ARGROW2(ARRAY,ICOL,IROW,I1,I2,J,%VAL(IPNT),ISIZE,
     1      TRIM,LLOG,VLO,VHI,IXOR,IYOR)
      CALL FRDATA('QROW',ISTATUS)
      END
C
