      SUBROUTINE ASP_XYPOS(IX,IY,ISTAT,ID)
C
C  THESE 3 ARRAYS ARE USED TO SET UP THE ARGS OVERLAYS.
C   IN GENERAL THEY SHOULD NOT BE NEEDED, BUT IN THIS CASE
C   IT IS DESIRABLE THAT THE CURSOR SHOULD NOT CLEAR THE OVERLAY
C   PLANES.
C
      INTEGER*2 IOFF(3),ION(3),IFLIP(3)
      DATA IOFF,ION,IFLIP/3*0,'0010'X,'0008'X,'0003'X,3*0/
C
C   ROUTINE WHICH CALLS THE TIME-OUT CURSOR
C   IF THE ARGS CURSOR DOES NOT MOVE IN 5 SECS.
C   IT IS AS IF BUTTON "0" HAD BEEN PRESSED.
C   AND A BAD STATUS IS RETURNED
C
C   THIS ROUTINE WOULD NORMALLY BE REPLACED BY A CALL TO
C      ARGS_CUROP('1234','G')
C
      CALL ARGS_VSR(IOFF,ION,IFLIP)
      CALL ARGS_CURTO(' ',ID,IB,UX,UY)
      IF (IB.EQ.0) THEN
         ISTAT=1
      ELSE
         ISTAT=0
      END IF
      CALL ARGS_CURCL
      IX=UX
      IY=UY
      END
