	SUBROUTINE CRB_APAN
 
*+
*
*  - - - - - -
*  :  A P A N :
*  - - - - - -
*
*
*   ARGS TRACKERBALL/CURSOR PAN AND ZOOM PACKAGE
*
*
*	EXECUTION CONTINUES UNTIL BUTTON 4 IS PRESSED
*
*	BUTTON 3 INCREASES THE X AND Y ZOOM FACTORS
*	BUTTON 2 DECREASES THE X AND Y ZOOM FACTORS
*	BUTTON 1 RESETS THE ZOOM FACTORS AND IMAGE POSITION
*
*	ZOOM FACTORS ALLOWED ARE 1,2,4,8,16
*
*	RETURNED
*
*	IX,IY POSITION OF CURSOR ON IMAGE
*
*
*    D.J.KING   R.G.O.   DEC 81
*
*-
	INTEGER STATUS,AX,AY
	REAL UX,UY
 
*  ALLOCATE ARGS
 
	CALL SRINIT(0,.FALSE.,STATUS)
	IF (STATUS.NE.0) THEN
		CALL WRERR('NOARGS')
	ELSE
	CALL BLABELS(9,'Y','RESET','SMALLER',
     1'BIGGER','EXIT')
		CALL ASP_PAN(AX,AY,UX,UY)
	ENDIF
 
* SEND COORDS TO ENVIRONMENT
 
	CALL WRKEYI ('AX',AX,1,STATUS)
	CALL WRKEYI ('AY',AY,1,STATUS)
	CALL WRKEYR ('X',UX,1,STATUS)
	CALL WRKEYR ('Y',UY,1,STATUS)
 
	CALL ARGS_OVCLR(9)
	END
 
C
 
*
*  ADHC IMAGE [XCENTRE] [YCENTRE] [SHADE]
*
*  VERSION OF DISP PROGRAM BUT PERMITTING DISPLAY CENTRED
*  ON ANY ARGS COORDINATES XC, YC AND ALSO
*  UPDATING ARGS DATABASE FILE
*
*  ORIG PTW MODIF FOR DATABASE BY WFL JULY 1981
*
*
*  MODIFIED BY WDP TO AUTOMATICALLY SCALE IMAGE
*    (DOES A "HISTOGRAM EQUALIZATION") TO
*    PRODUCE VERY HIGH CONTRAST IMAGE ON ARGS.  USEFUL FOR
*    EXAMINING FAINT STRUCTURE NEAR THE BACKGROUND LEVEL
*
*   EXPERIMENTAL VERSION USING 'DATA STRUCTURE'
*
