	SUBROUTINE CRB_LUTROT
 
	INTEGER STAT,DIM(2),OFFSET
 
 
 
*  ALLOCATE ARGS
	CALL SRINIT(0,.FALSE.,JSTAT)
	IF (JSTAT.NE.0) THEN
		CALL WRERR('NOARGS')
	ELSE
	CALL BLABELS(9,'Y','RESET',' ',' ','EXIT')
		CALL ASP_LUTROT(OFFSET)
		CALL WRKEYI('OFFSET',OFFSET,1,STATUS)
	CALL ARGS_OVCLR(9)
	ENDIF
 
	END
 
C
C
*CALLS
*	THIS PACKAGE:
*		GETPAR,GTXYLR,EXTLST,XYINCA,GTXYLW,ADDLST,LBGONE,GTDSCR,
*		PTDSCR
*	STARLINK:
*		GETDYN,WRERR,WRUSER,RDKEYC,CYDSCR,FRDATA
*       ARGSLIB:
*               SRINIT
*	ASPIC:
*		ASP_PAN
*
*NOTES
*	USES VAX %VAL FACILITY
*
*WRITTEN BY
*	R.F. WARREN-SMITH
*ADAPTED BY
*     A.J. PENNY
* ----------------------------------------------------------------------
C
C
C
