	SUBROUTINE CRB_PEEP
      INTEGER IDIMN(99)
      INCLUDE 'INTERIM(FMTPAR)'
 
 
*  PREPARE TO READ IMAGE AND ENSURE 2-D
      CALL RDIMAG('IMAGE',FMT_R,99,IDIMN,NDIMS,IPIN,JSTAT)
      IF (NDIMS.NE.2) THEN
         CALL WRUSER('MUST BE 2D IMAGE!',J)
      ELSE
 
*     PICK UP CENTRE X,Y
         CALL RDKEYI('X0',.FALSE.,1,IX0,NVALS,JSTAT)
         CALL RDKEYI('Y0',.FALSE.,1,IY0,NVALS,JSTAT)
 
*     PICK UP FACTOR
         FACTOR=1.0
         CALL RDKEYR('FACTOR',.FALSE.,1,FACTOR,NVALS,JSTAT)
 
*     PRINT REGION
         CALL PEEP(%VAL(IPIN),IDIMN(1),IDIMN(2),IX0,IY0,FACTOR)
 
*     WRAP UP
         CALL FRDATA(' ',JSTAT)
      END IF
	CALL CNPAR('X0',ISTAT)
	CALL CNPAR('Y0',ISTAT)
 
      END
 
