*******************************************************
*  HELP: CALLS HELP LIBRARY
*****************************
      SUBROUTINE CRB_HELP
*
*   GETHELP.FOR
*
*   30 JULY 1986
*
*   LOOKS UP AND DISPLAYS HELP TEXT FROM SYS$HELP:HELPLIB.HLB
*
	IMPLICIT INTEGER*4 (A-Z)
	INTEGER*4 KEY_LEN(3)
	PARAMETER LBR$C_READ='0001'X
	CHARACTER*32 KEY(3)
*
*   INITIALISE THE LIBRARIAN
*
	STATUS=LBR$INI_CONTROL(INDEX,LBR$C_READ)
	IF(.NOT.STATUS) CALL LIB$STOP(%VAL(STATUS))
*
*   OPEN HELP LIBRARY
*
	STATUS=LBR$OPEN(INDEX,
	1               'SYS$HELP:HELPLIB.HLB')
	IF(.NOT.STATUS) CALL LIB$STOP(%VAL(STATUS))
*
*   GET HELP KEYS
*
	DO I=1,3
		TYPE 10,I
10		FORMAT('$Enter Key',I2,': ')
		ACCEPT 20, KEY_LEN(I),KEY(I)
20		FORMAT(Q,A)
	ENDDO
*
*   LOCATE AND PRINT THE HELP TEXT
*
	STATUS=LBR$GET_HELP(INDEX,,,,
	1	            KEY(1) (1:KEY_LEN(1)),
	
	1      		    KEY(2) (1:KEY_LEN(2)),
	1		    KEY(3) (1:KEY_LEN(3)))
	IF(.NOT.STATUS) CALL LIB$STOP(%VAL(STATUS))
*
*   CLOSE THE LIBRARY
*
	STATUS=LBR$CLOSE(INDEX)
	IF(.NOT.STATUS) CALL LIB$STOP(%VAL(STATUS))
	END
