	SUBROUTINE CRB_ADISOV
 
      INTEGER STATUS,PLANE,I
      DATA PLANE/8/
 
      CALL SRINIT (0,.FALSE.,STATUS)
 
      IF (STATUS.EQ.0) THEN
          CALL RDKEYI ('PLANE',.TRUE.,1,PLANE,I,STATUS)
          CALL ARGS_OVCL (PLANE,.TRUE.)
      ENDIF
 
      END
