	SUBROUTINE CRB_AFLASH
      INTEGER IDIMN(99)
      LOGICAL TRIM,LLOG
      CHARACTER VALUE*80
      CHARACTER*1 CRBANS
	CHARACTER*6 ANS
	INTEGER ISTAT
      INCLUDE 'INTERIM(FMTPAR)'
      INCLUDE 'INTERIM(ERRPAR)'
201   CALL CNPAR('IMAGE',JSTAT)
      CALL SRINIT(0,.FALSE.,JSTAT)
      IF (JSTAT.NE.0) THEN
         CALL WRUSER('DISPLAY UNAVAILABLE',JSTAT)
      ELSE
         CALL WRUSER('NAME OF IMAGE FILE TO BE DISPLAYED=?',JSTAT)
         CALL RDIMAG('IMAGE',102,99,IDIMN,NDIMS,IPIN,JSTAT)
         IF (NDIMS.NE.2) THEN
            CALL WRUSER('MUST BE 2D IMAGE!',J)
         ELSE
            IXC=256
            IYC=256
            CALL WRUSER('IMAGE POSITION ON ARGS=?',JSTAT)
            CALL RDKEYI('XC',.TRUE.,1,IXC,NVALS,JSTAT)
            CALL RDKEYI('YC',.TRUE.,1,IYC,NVALS,JSTAT)
            CALL AFLASH2(%VAL(IPIN),IDIMN(1),IDIMN(2),IXC,IYC)
            CALL FRDATA(' ',JSTAT)
C
C           UPDATE THE ARGS DATABASE
C
            CALL ARGS_WRIM (IXC,IYC,IDIMN(1),IDIMN(2),IDIMN(1),IDIMN(2),
     &         JSTAT)
            IF(JSTAT.NE.0)THEN
               CALL WRUSER('COULDN''T UPDATE ARGS DATABASE',JSTAT)
            ENDIF
         END IF
      ENDIF
	CALL CNPAR('XC',JSTAT)
	CALL CNPAR('YC',JSTAT)
	END
C
C
C+	PROGRAM TO COMPLETELY RESET THE ARGS DISPLAY
C
C	NO ARGUMENTS
C       RESETS THE ARGS CURRENTLY ASSIGNED TO ARGS_DEVICE
C
C	WFL JAN 1981 MODIF JULY 1981 TO ACCESS ARGS DATABASE
C
C
C-
C
C
