	SUBROUTINE CRB_ARESET
      INTEGER IDIMN(99)
      LOGICAL TRIM,LLOG
      CHARACTER VALUE*80
      CHARACTER*1 CRBANS
	CHARACTER*6 ANS
	INTEGER ISTAT
      INCLUDE 'INTERIM(FMTPAR)'
      INCLUDE 'INTERIM(ERRPAR)'
203   CALL SRINIT(0,.TRUE.,ISTAT)
	IF (ISTAT.EQ.0) THEN
		CALL ARGS_CLRIM(ISTAT)
	ENDIF
	END
C
C  Subroutine HELPADVICE fetches information from HELP library
C  N = 1 for ASPIC HELP library
C  N = 2 for CRB's HELP library
C
