      SUBROUTINE CROSSA (ID,X,Y,NUM)
C
C DRAW A CROSS ON ARGS AT POSITION (X,Y) (USER UNITS) OF WIDTH 5
C PIXELS. (ID IS ID OF IMAGE)
C AND NUMBER IT
C
      INTEGER KPX,KPY,STATUS
      CHARACTER*72 TEXT
      REAL X,Y,UX,UY,DX,DY,XVAL(2),YVAL(2)
      CALL ARGS_UTOP (ID,X,Y,KPX,KPY,STATUS)
      CALL ARGS_PTOU (ID,KPX+2,KPY+2,UX,UY,STATUS)
      DX = UX - X
      DY = UY - Y
      XVAL(1) = X - DX
      YVAL(1) = Y
      XVAL(2) = X + DX
      YVAL(2) = Y
      CALL ARGS_POLYL (ID,2,XVAL,YVAL,STATUS)
      XVAL(1) = X
      YVAL(1) = Y - DY
      XVAL(2) = X
      YVAL(2) = Y + DY
      CALL ARGS_POLYL (ID,2,XVAL,YVAL,STATUS)
C
      DO K = 1,72
         TEXT(K:K) = ' '
      ENDDO
      WRITE(TEXT,900)NUM
  900 FORMAT(I10)
      KSHIFT = 0
      DO K = 1,9
         IF(TEXT(K:K).EQ.' ') KSHIFT = K
      ENDDO
      DO K = 1,10
         J = K + KSHIFT
         TEXT(K:K) = TEXT(J:J)
      ENDDO
      CALL ARGS_UTOP(ID,X,Y,KPX,KPY,STATUS)
      CALL ARGS_PTOU(ID,KPX+3,KPY+3,UXA,UYA,STATUS)
      KX = UXA
      KY = UYA
      CALL ARGTXT(TEXT,'B',0,KX,KY,0)
C
C
C
      END
 
 
 
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
