      SUBROUTINE GREY(IRAY,ICOL,IROW,NCOL,NROW,MINC,MAXC,
     1 MINR,MAXR,CONVERT,NUNIT)
C
C *****************************************************************
C
C     DEFINES PARAMETERS AND ARRAYS FOR MAKING A GREY SCALE PLOT
C     ON THE VERSATEC OR PRINTRONIX PRINTER/PLOTTER
C
C     WRITTEN BY W D PENCE, UNIV. OF SUSSEX, OCT 1980
C
C     IRAY = 2 DIMENSIONAL IMAGE ARRAY (R*4)
C     ICOL = SIZE OF THE FIRST DIMENSION OF IRAY (I*4)
C     IROW = SIZE OF THE SECOND DIMENSION OF IRAY (I*4)
C     NCOL = ACTUAL NUMBER OF COLUMNS IN IRAY (.LE. ICOL)
C     NROW = ACTUAL NUMBER OF ROWS (RECORDS) IN IRAY (.LE. IROW)
C   THE FOLLOWING FOUR PARAMETERS DEFINE A WINDOW AREA WITHIN THE ARRAY
C     MINC = FIRST COLUMN OF IRAY WITHIN THE WINDOW
C     MAXC = LAST COLUMN
C     MINR = FIRST ROW
C     MAXR = LAST ROW
C     CONVERT = CONVERSION FACTOR BETWEEN IRAY UNITS AND PHYSICAL
C         INTENSITY UNITS:  INTENSITY = IRAY/CONVERT
C
C     USES SUBROUTINE STOCHPN, ORIGINALLY WRITTEN BY K. HARTLEY, RGO
C     LINK WITH NAG LIBRARY.
C
C *********************************************************************
C
      PARAMETER INTICK=20
      PARAMETER  NINTER=200
      REAL*4 IRAY(ICOL,IROW)
      REAL IV,MINVAL,MAXVAL
      DIMENSION VAL(NINTER),XHIS(NINTER),SIG(NINTER),A(10),
     1 NHIS(NINTER),DAT(2200)
      DOUBLE PRECISION VAL,XHIS,SIG,A,CHI,RMS,XVAL
      CHARACTER ANS*1,TYPE*8,BUFFER*80,DEVICE,CR*1,LF*1
      CHARACTER LABEL*80
      LOGICAL DEFAULT,ROTATE,MAXINF,LOG
C
      DATA CR,LF/'0D'X,'0A'X/
C
      IF (NUNIT .LT. 0)THEN
        MAXDOTS=786
        WIDE=13.1
      ELSE
        MAXDOTS=2112
        WIDE=10.56
      END IF
C     MAXDOTS = NO. OF PRINTER PIXELS ACROSS WHOLE LENGTH OF PAGE
C     WIDE = WIDTH OF PAGE IN INCHES
C
C
17    CALL WRUSER(' ',IS)
      CALL WRUSER('ASSUME DEFAULT VALUES FOR',IS)
      CALL WRUSER('    ROTATION',IS)
      CALL WRUSER('    WINDOW SIZE',IS)
      CALL WRUSER('    PIXEL SIZE',IS)
      CALL WRUSER('      AND',IS)
      CALL WRUSER('    INTENSITY SCALING?',IS)
      DEFAULT=.TRUE.
      CALL RDKEYL('DEFAULT',.TRUE.,1,DEFAULT,NVAL,IS)
C
      IF (DEFAULT)THEN
        ROTATE=.FALSE.
      ELSE
2       CALL WRUSER('ROTATE PICTURE 90 DEGREES?  (Y/N)',IS)
        ROTATE=.FALSE.
        CALL RDKEYL('ROTATE',.TRUE.,1,ROTATE,NVAL,IS)
C
C       OPTION TO CHANGE THE WINDOW
C
        CALL WINDOWQ(MINC,MAXC,MINR,MAXR,NCOL,NROW)
      END IF
C
16    IF (ROTATE)THEN
        KWIDE=MAXR-MINR+1
      ELSE
        KWIDE=MAXC-MINC+1
      END IF
      IF (KWIDE .GT. MAXDOTS-12)THEN
        WRITE(BUFFER,3000)MAXDOTS-12
3000    FORMAT('ERROR: MAX WIDTH OF PLOT IS',I5,' PIXELS')
        CALL WRUSER(BUFFER,IS)
        RETURN
      END IF
C
C    DETERMINE LENGTH OF TICK MARKS, IN PIXEL UNITS
C
      LENTICK=6/((MAXDOTS-12)/(KWIDE))
      LENTICK=MAX(LENTICK,1)
      NSAMP=KWIDE+2*LENTICK
      IWIDTH=MAXDOTS/NSAMP
C
      IF (DEFAULT)THEN
        NGRID=1000000
        IHIGH=IWIDTH
      ELSE
        CALL RDKEYI('GRID',.TRUE.,1,NGRID,NV,IS)
        IF (NGRID .EQ. 0)NGRID=1000000
65      WRITE(BUFFER,3001)IWIDTH
3001    FORMAT('EACH PIXEL WILL BE',I4,' DOTS WIDE (ACROSS PAPER)')
        CALL WRUSER(BUFFER,IS)
        CALL WRUSER('HOW MANY DOTS HIGH SHOULD EACH PIXEL BE?',IS)
        IHIGH=IWIDTH
        CALL RDKEYI('PIXEL',.TRUE.,1,IHIGH,NVAL,IS)
        IF (IHIGH .LT. 1 .OR. IHIGH .GT. MAXDOTS)GO TO 65
      END IF
      RATIO=(IHIGH+.01)/IWIDTH
C
      CALL RDKEYC('LABEL',.FALSE.,1,LABEL,NVAL,IS)
C
C     FIND MIN AND MAX VALUES WITHIN THE WINDOW
C
      MINVAL=1000000
      MAXVAL=-1000000
      DO 10 I=MINR,MAXR
      DO 10 J=MINC,MAXC
            IV=IRAY(J,I)
            MINVAL=MIN(MINVAL,IV)
10    MAXVAL=MAX(MAXVAL,IV)
      IF (MINVAL .EQ. MAXVAL)THEN
            CALL WRUSER('ERROR: ALL THE PIXELS HAVE THE SAME VALUE',IS)
            RETURN
      END IF
      MAXVAL=MAXVAL+1
C
      MAXINF=.TRUE.
      IF (.NOT. DEFAULT)THEN
        CALL WRUSER('MAKE A "MAXIMUM INFORMATION" PICTURE?',IS)
        CALL RDKEYL('MAXINF',.TRUE.,1,MAXINF,NVAL,IS)
      END IF
      IF (MAXINF)THEN
         YZERO=1.5
C          YZERO CONTROLS SHAPE OF HISTOGRAM OF OUTPUT DENSITIES
C          YZERO=1, FLAT HISTOGRAM
C          YZERO=0, STRONGLY WEIGHTED TOWARDS BLACK
C          YZERO=2, STRONGLY WEIGHTED TOWARDS WHITE
C        COEFFICIENTS OF QUADRATIC EQUATION TO BE SOLVED:
         B=YZERO
         AQ=1.-YZERO
         A2=2.*AQ
         A4=4.*AQ
         B2=B*B
C
C        COMPUTE 200 INTERVAL HISTOGRAM WITHIN RANGE
C
         NCYCLES=0
         CALL WRUSER('COMPUTING HISTOGRAM OF PIXEL VALUES...',IS)
12       WRITE(BUFFER,3003)MINVAL/CONVERT,MAXVAL/CONVERT
3003     FORMAT('MIN AND MAX VALUES =',2F14.4)
         CALL WRUSER(BUFFER,IS)
         LOWPTS=0
         DO 15 I=1,NINTER
15       NHIS(I)=0
         XINTER=NINTER
         DX=(MAXVAL-MINVAL)/XINTER
         DO 20 I=MINR,MAXR
         DO 20 J=MINC,MAXC
            IV=IRAY(J,I)
            K=(IV-MINVAL)/DX+1.
            IF (K .LT. 1 )THEN
              LOWPTS=LOWPTS+1
            ELSE IF (K .LE. NINTER)THEN
              NHIS(K)=NHIS(K)+1
            END IF
20       CONTINUE
C
C        COMPUTE NORMALIZED CUMULATIVE HISTOGRAM
C
         PTS=(MAXR-MINR+1)*(MAXC-MINC+1)
         NHIS(1)=NHIS(1)+LOWPTS
         DO 30 I=2,NINTER
30       NHIS(I)=NHIS(I)+NHIS(I-1)
         DO 35 I=1,NINTER
            VAL(I)=MINVAL+I*DX
            XHIS(I)=NHIS(I)/PTS
35       CONTINUE
C
C        FIT 6 TERM POLYNOMIAL TO CUMULATIVE DIST. FUNC. IN RANGE
C         OF 2 TO 96 PERCENT
C
         J=0
         DO 40 I=1,NINTER
            IF (XHIS(I) .GT. .02 .AND. (XHIS(I) .LT. .96
     1       .OR. J .EQ. 0))THEN
               J=J+1
               XHIS(J)=XHIS(I)
               VAL(J)=VAL(I)
            END IF
40       CONTINUE
         J=MAX(1,J)
         MAXVAL=VAL(J)
         MINVAL=VAL(1)
         WRITE(BUFFER,3004)J
3004     FORMAT(I5,' HISTOGRAM BINS IN 2-96 PERCENT RANGE')
         CALL WRUSER(BUFFER,IS)
C
C        IF THERE ARE LESS THAN 20 BINS IN THE HISTOGRAM, THEN
C        REDO HISTOGRAM WITH NARROWER LIMITS
C
         IF (J .LT. 20 .AND. NCYCLES .LE. 2)THEN
            NCYCLES=NCYCLES+1
            MINVAL=MINVAL-2.*DX
            MAXVAL=MAXVAL+DX
            GO TO 12
         END IF
C
         IF (J .LT. 7)THEN
           CALL WRUSER('FAILED DUE TO PECULIAR PIXEL DISTRIBUTION',
     1      IS)
           RETURN
         END IF
C
C        FOR MAX. PRECISION, NORMALIZE VAL TO RANGE 0-1
C
         DELX=VAL(J)-VAL(1)
         XFST=VAL(1)
         DO 45 I=1,J
45       VAL(I)=(VAL(I)-XFST)/DELX
C
         CALL POLFIT(VAL,XHIS,SIG,J,6,0,A,CHI,RMS)
         XFLO=MINVAL/CONVERT
         XHI=MAXVAL/CONVERT
         FLO=0.
         HI=1.
         XMID=.5
         TYPE='MAX INFO'
         TYP=999.
         WRITE(BUFFER,3005)XFLO,XHI
3005     FORMAT('GREY SCALE RANGES FROM',F14.4,' TO',F14.4)
         CALL WRUSER(BUFFER,IS)
C
      ELSE
C
         XFLO=MINVAL/CONVERT
         XHI=MAXVAL/CONVERT
         WRITE(BUFFER,3006)XFLO,XHI
3006     FORMAT('PIXELS RANGE FROM',F14.4,' TO',F14.4)
         CALL WRUSER(BUFFER,IS)
         CALL WRUSER('LEVEL TO CORRESPOND TO PURE WHITE=?',IS)
         CALL RDKEYR('WHITE',.TRUE.,1,XFLO,NVAL,IS)
         CALL WRUSER('LEVEL TO CORRESPOND TO PURE BLACK=?',IS)
         CALL RDKEYR('BLACK',.TRUE.,1,XHI,NVAL,IS)
C
         LOG=.FALSE.
         IF (XFLO .GT. 0. .AND. XHI .GT. 0.)THEN
           CALL WRUSER('PLOT ON A LOG INTENSITY SCALE?',IS)
           CALL RDKEYL('LOG',.TRUE.,1,LOG,NVAL,IS)
         END IF
         IF (LOG)THEN
            TYPE='LOG'
            TYP=2.
         ELSE
            TYPE='LINEAR'
            TYP=1.
         END IF
C
         IF (XHI .LT. XFLO)THEN
            XTEM=XHI
            XHI=XFLO
            XFLO=XTEM
            TYP=-TYP
         END IF
C
         FLO=XFLO*CONVERT
         HI=XHI*CONVERT
         XMID=(FLO+HI)/2.
         IF (LOG)XMID=10.**(LOG10(FLO)+LOG10(HI))/2.
      END IF
C
C     PLOT FROM TOP TO BOTTOM
C
      IF (NUNIT .LT. 0)THEN
        OPEN(UNIT=(-NUNIT),NAME='GREYPLT.LIS',TYPE='NEW',
     1    CARRIAGECONTROL='NONE',RECL=134    )
      ELSE
        OPEN(UNIT=NUNIT,NAME='DIT.DAT',RECORDSIZE=265/4+1,
     1   STATUS='NEW',CARRIAGECONTROL='NONE',FORM=
     2   'UNFORMATTED',RECORDTYPE='FIXED')
      END IF
      CALL STINIT(IDUMMY)
C
      IF (ROTATE)THEN
        I1=MAXR
        I2=MINR
        ID=-1
        J1=MAXC
        J2=MINC
      ELSE
        I1=MINC
        I2=MAXC
        ID=1
        J1=MAXR
        J2=MINR
      END IF
C
C     PRINT TICK MARK AT TOP OF PICTURE
C
      K=LENTICK
      DO 80 J=I1,I2,ID
        K=K+1
        IF (MOD(J,INTICK) .EQ. 0)THEN
          DAT(K)=HI
        ELSE
          DAT(K)=FLO
        END IF
80    CONTINUE
      DO 85 J=1,LENTICK
        DAT(J)=FLO
        DAT(K+J)=FLO
85    CONTINUE
      DO 88 J=1,LENTICK
        CALL STOCHPN(DAT,FLO,HI,NSAMP,TYP,WIDE,1.,NUNIT)
88    CONTINUE
C
      DO 100 I=J1,J2,-1
      IYGRID=MOD(I,NGRID)
      K=LENTICK
      DO 90 J= I1,I2,ID
      IXGRID=MOD(J,NGRID)
      K=K+1
      IF (ROTATE)THEN
        IV=IRAY(I,J)
      ELSE
        IV=IRAY(J,I)
      END IF
      IF (TYP .EQ. 999)THEN
         IF (IV .LT. MINVAL)THEN
            DAT(K)=0.
         ELSE IF (IV .LT. MAXVAL)THEN
            XVAL=(IV-XFST)/DELX
            DAT(K)=((((A(6)*XVAL+A(5))*XVAL+A(4))*XVAL+A(3))*XVAL+A(2))
     1       *XVAL+A(1)
            IF (YZERO .NE. 1.)DAT(K)=(-B+SQRT(B2+A4*DAT(K)))/A2
         ELSE
            DAT(K)=1.
         END IF
      ELSE
        DAT(K)=IV
      END IF
C
C     ADD GRID LINES
C
      IF (IYGRID .EQ. 0 .OR. IXGRID .EQ. 0)THEN
            IF (DAT(K) .LT. XMID)THEN
              DAT(K)=HI
            ELSE
              DAT(K)=FLO
            END IF
      END IF
90    CONTINUE
C
C     ADD TICK MARKS
C
      DO 95 J=1,LENTICK
      IF (MOD(I,INTICK) .EQ. 0)THEN
        DAT(J)=HI
        DAT(K+J)=HI
      ELSE
        DAT(J)=FLO
        DAT(K+J)=FLO
      END IF
95    CONTINUE
C
      IF (MOD(I,20).EQ.0)THEN
        WRITE(BUFFER,3007)I
3007    FORMAT('LINE ',I5)
        CALL WRUSER(BUFFER,IS)
      END IF
      CALL STOCHPN(DAT,FLO,HI,NSAMP,TYP,WIDE,RATIO,NUNIT)
100   CONTINUE
C
C     PRINT TICK MARKS AT BOTTOM
C
      K=LENTICK
      DO 110 J=I1,I2,ID
        K=K+1
        IF (MOD(J,INTICK) .EQ. 0)THEN
          DAT(K)=HI
        ELSE
          DAT(K)=FLO
        END IF
110   CONTINUE
      DO 115 J=1,LENTICK
        DAT(J)=FLO
        DAT(K+J)=FLO
115   CONTINUE
      DO 120 J=1,LENTICK
        CALL STOCHPN(DAT,FLO,HI,NSAMP,TYP,WIDE,1.,NUNIT)
120   CONTINUE
C
      IF (NUNIT .LT. 0)THEN
        LUNIT=ABS(NUNIT)
      ELSE
        LUNIT=19
        OPEN(UNIT=LUNIT,NAME='DIT.LIS',TYPE='NEW',RECL=134,
     1       CARRIAGECONTROL='NONE')
      END IF
      WRITE(LUNIT,2001)CR,LF,LABEL,CR,LF
      IF (TYP .LT. 0.)THEN
        XTEM=XFLO
        XFLO=XHI
        XHI=XTEM
      END IF
      WRITE(LUNIT,1005)MINC,MAXC,CR,LF,MINR,MAXR,CR,LF,XFLO,XHI,CR,LF
      IF (ROTATE)THEN
        WRITE(LUNIT,1003)CR,LF
      END IF
      IF (NGRID .LT. 1000000)THEN
        WRITE(LUNIT,1002)NGRID,CR,LF
      END IF
      WRITE(LUNIT,1004)INTICK,CR,LF
      WRITE(LUNIT,1009)IWIDTH,IHIGH,CR,LF
      WRITE(LUNIT,1007)TYPE,CR,LF
2001  FORMAT(2A1,A80,2A1)
1005  FORMAT(
     1 '  PICTURE OF COLUMNS:',2I5,2A1,12X,'AND ROWS:',2I5,2A1,
     2 '  PURE WHITE =',F12.3,', PURE BLACK =',F12.3,2A1)
1003  FORMAT(' PICTURE ROTATED 90 DEGREES COUNTER-CLOCKWISE',2A1)
1002  FORMAT('  GRID LINES ARE DRAWN AT MULTIPLES OF',I5,' PIXELS',2A1)
1004  FORMAT('  TICK MARKS ARE DRAWN AT MULTIPLES OF',I5,' PIXELS',2A1)
1009  FORMAT('  EACH PIXEL IS',I3,' DOTS WIDE BY',I3,' DOTS HIGH',2A1)
1007  FORMAT('  PLOT IS ON A ',A,' INTENSITY SCALE.',2A1)
      IF (NUNIT .LT. 0)THEN
       CLOSE(UNIT=(-NUNIT))
       ISTATUS=LIB$DO_COMMAND('$PRINT/QUEUE=SYS_PRINTRONIX/NOFEED/PASSAL
     1  GREYPLT')
      ELSE
        CLOSE(UNIT=NUNIT)
        CLOSE(UNIT=LUNIT)
        ISTATUS=LIB$DO_COMMAND('$PRINT/QUEUE=SYS_VERSATEC/NOFEED/PASSALL
     1    DIT.DAT ,DIT.LIS')
      END IF
	CALL CNPAR('INPUT',JSTAT)
	CALL CNPAR('LABEL',JSTAT)
	CALL CNPAR('DEVICE3',JSTAT)
      END
C****************************************************************
