	SUBROUTINE HANDLE(XNEXT,X,RGB,GREYLUT,OUTLUT,ICOLS)
C
C+      ROUTINE TO UPDATE THE LUT AND WRITE IT.
C
	IMPLICIT INTEGER (A-Z)
	INTEGER RGB(3,0:255),GREYLUT(3,0:255),OUTLUT(3,0:255)
	REAL X
C
C   NOTE THAT (1) ONE OF THESE LOOPS WILL BE OF ZERO LENGHTH
C                 AND SO NOT EXECUTED.
C             (2) ANY DELETED COLOURS ARE FILLED WITH GREY ENTRIES.
C
	DO J=XNEXT,X
		DO K=1,3
			OUTLUT(K,J)=RGB(K,ICOLS)
		ENDDO
		CALL SRCOL1(J,RGB(1,ICOLS),RGB(2,ICOLS),RGB(3,ICOLS))
	ENDDO
	DO J=X+1,XNEXT-1
		DO K=1,3
			OUTLUT(K,J)=GREYLUT(K,J)
		ENDDO
		CALL SRCOL1(J,GREYLUT(1,J),GREYLUT(2,J),GREYLUT(3,J))
	ENDDO
	XNEXT=X+1
999	RETURN
	END
