C
C  Subroutine HELPADVICE fetches information from HELP library
C  N = 1 for ASPIC HELP library
C  N = 2 for CRB's HELP library
C
	SUBROUTINE HELPADVICE(N)
	IMPLICIT INTEGER*4 (A-Z)
	CHARACTER*32 HELP
	CHARACTER*32 KEY
	EXTERNAL LIB$PUT_OUTPUT,LIB$GET_INPUT
	INCLUDE '($HLPDEF)'
	IF(N.EQ.1) HELP='ASPDIR:PROGLIB.HLB'
	IF(N.EQ.2) HELP='U1:[CRB.SYS]RGO.HLB'
	PRINT *,'On what subject do you wish to be advised?'
	PRINT *,'(Press RETURN for a topic list)'
	READ(5,101) KEY
101	FORMAT(A32)
	FLAGS=HLP$M_HELP.OR.HLP$M_PROCESS.OR.HLP$M_PROMPT
	STATUS=LBR$OUTPUT_HELP(LIB$PUT_OUTPUT,,KEY,
	1   HELP,FLAGS,LIB$GET_INPUT)
	IF(.NOT.STATUS) CALL LIB$STOP(%VAL(STATUS))
	END
