      SUBROUTINE HRDCOPY(IRAY,ICOL,IROW,LABEL,SQUARE,THRESH)
C
C     HRDCOPY:
C     DEFINES PARAMETERS AND ARRAYS FOR MAKING A GREY SCALE PLOT
C     ON THE  PRINTRONIX PRINTER/PLOTTER
C
C     IRAY = 2 DIMENSIONAL IMAGE ARRAY (I*2)
C     ICOL = SIZE OF THE FIRST DIMENSION OF IRAY (I*4)
C     IROW = SIZE OF THE SECOND DIMENSION OF IRAY (I*4)
C
      PARAMETER WIDE=13.1, NUNIT=8
C
C     WIDE = WIDTH OF PAGE IN INCHES
C
      LOGICAL SQUARE
      INTEGER THRESH,FF
      INTEGER*2 IRAY(ICOL,IROW)
      DIMENSION DAT(2200)
      CHARACTER LABEL*80
      DATA FF/'0A'X/
C
C     PLOT FROM TOP TO BOTTOM
C
      OPEN(UNIT=NUNIT,NAME='AHARDCOPY.LIS',TYPE='NEW',
     :     RECL=134,CARRIAGECONTROL='NONE')
C
	IF (THRESH.LT.O) THEN
		THRESH=-THRESH
		ISIGN=-1
	ELSE
		ISIGN=1
	ENDIF
      DO 100 J=IROW,1,-1
        K=0
        DO 90 I=1,ICOL
          K=K+1
	  IF (IRAY(I,J).GT.THRESH) THEN
		IF (ISIGN.EQ.1) THEN
			DAT(K)=1
		ELSE
			DAT(K)=0
		ENDIF
	  ELSE
		IF (ISIGN.EQ.1) THEN
			DAT(K)=0
		ELSE
			IF (IRAY(I,J).EQ.0) THEN
				DAT(K)=0
			ELSE
				DAT(K)=1
			ENDIF
		ENDIF
	  ENDIF
 90     CONTINUE
        IF (MOD(J,5) .EQ. 0 .AND. SQUARE)THEN
C
C       REPEAT EVERY FIFTH LINE ON THE PRINTRONIX SO PLOT IS SQUARE
C
          ITWO=2
        ELSE
          ITWO=1
        END IF
        CALL PLOTIT(DAT,K,NUNIT,ITWO)
100   CONTINUE
C
      WRITE(NUNIT,2000) FF
2000  FORMAT(1X,A1)
      WRITE(NUNIT,2001) LABEL,FF
2001  FORMAT(10X,A,A1)
      CLOSE(UNIT=NUNIT)
C
      END
C***********************************************************************
