      SUBROUTINE LINPLOT(LINE,NPTS)
      REAL LINE(0:NPTS-1),AX(2),AY(2)
C
C   GET SCALING PARMS
C
      FMAX = LINE(0)
      FMIN = 0.0
      DO 100 I=0,NPTS
      IF(LINE(I).GT.FMAX)  FMAX = LINE(I)
      IF(LINE(I).LT.FMIN)  FMIN = LINE(I)
  100 CONTINUE
C
C   PREPARE FOR PLOTTING
C
      AX(1) = 0.0
      AX(2) = REAL(NPTS-1)
      AY(1) = FMIN
      AY(2) = 1.2*FMAX
      CALL JBDEV('GKS_15_0')
      CALL JBAXES(AX,2,20.,5HPIXEL,5,AY,2,15.,1H ,1)
C
C   PLOT DATA
C
      DO 200 I=0,NPTS-1
      CALL JOIN PT(REAL(I),LINE(I))
  200 CONTINUE
C
      END
C
