      SUBROUTINE LINSET(X1,X2,Y1,Y2,LINDAT,NPTS)
C
      REAL LINDAT(0:1023,2)
C
      PARAMETER (RAD=57.29578)
C
C   CALCULATE THE X,Y POSITIONS OF POINTS AT RADII OF
C   INTEGRAL PIXEL SPACINGS FROM THE FIRST POINT
C
      THETA = ATAN2 (Y2-Y1,X2-X1)
      CT = COS(THETA)
      ST = SIN(THETA)
      SEP = SQRT ((X2-X1)**2 + (Y2-Y1)**2)
      NPTS = NINT (SEP)
C
      DO I=0,NPTS-1
        LINDAT(I,1) = I*CT + X1
        LINDAT(I,2) = I*ST + Y1
      ENDDO
      END
C
