      SUBROUTINE NEQSOL(X,Y,Z,NDIM,NP,NF,NOTO,IOOR,D,SE,
     1 RDOE,SDOR)
C
C **************************************************************
C
C     SUBROUTINE NEQSOL(X,Y,Z,NDIM,NP,NF,NOTO,IOOR,D,SE,RDOE,SDOR)
C
C THIS SUBROUTINE COMPUTES THE COEFFICIENTS, D, WHICH DEFINE THAT LINEAR
C FUNCTION, Y, OF LINEARLY INDEPENDENT FUNCTIONS WHICH BEST FITS, IN THE
C LEAST SQUARES SENSE, A GIVEN SET OF DATA. OR EQUIVALENTLY, IT FINDS
C THE SOLUTION TO THE SYSTEM OF NORMAL EQUATIONS WHICH IS CALLED THE
C NORMAL EQUATIONS SOLUTION.
C
C     WRITTEN AND DOCUMENTED BY:
C
C     JONES, W B, OBITTS, D L, GALLET, R M, AND DE VAUCOULEURS, G,
C     'ASTRONOMICAL SURFACE PHOTOMETRY BY NUMMERICAL MAPPING
C     TECHNIQUES', PUBLICATION OF THE ASTRONOMY DEPARTMENT, UNIV.
C     OF TEXAS, AUSTIN, SERIES II, VOL. I, NO. 8, FEB. 1967
C
C     MODIFIED BY W D PENCE, UNIV. OF SUSSEX, SEPT. 1980
C
C     X(NP,2) = COORDINATES OF POINTS: X(I,1) = X COORD.  (R*4)
C                                      X(I,2) = Y COORD.  (R*4)
C     Y(NP) = VALUE OF POINT AT X(NP,1),X(NP,2)  (R*4)
C     Z = SCRATCH ARRAY  (DOUBLE PRECISION, R*8)
C     NDIM = FIRST DIMENSION OF X, Y AND Z (I*4)
C     NP = NO. OF POINTS IN LEAST SQUARES FIT  (I*4)
C     NF = NO. OF COEFS TO BE SOLVED FOR  (I*4)
C     NOTO = NO. OF TOTAL ORTHOGONALIZATIONS TO PERFORM (I*4)
C     IOOR = POSITIVE INTEGER IF OPTIONAL OUTPUT IS REQUIRED
C     D(NF) = COEFFICIENTS OF THE POLYNOMIAL (DOUBLE PRECISION, R*8)
C     SE(K) = RMS OF FIT USING ONLY THE FIRST K COEFFICIENTS (R*8)
C     RDOE(NF) = INDICATES THE STATISTICAL SIGNIFICANCE OF EACH TERM (R*
C     SDOR = STANDARD DEVIATION OF RESIDUALS  (R*4)
C
C ***************************************************************
C
      IMPLICIT DOUBLE PRECISION (A-H),(O-Z)
      REAL X(NDIM,2),Y(NDIM),SDOR,XGGG,YGGG
      DOUBLE PRECISION Z(NDIM),D(30)
      DIMENSION A(30),AKJ(30,30),AA(30),CE(30),DT(30),DYGC(30),
     1 GGSQT(30),GG(30,30),Q(30,30,2),RDOE(30),REE(30),RREE(30),RYG(30),
     2 SD(30),SE(30),S(30,30),YGC(30),YG(30)
      GO TO  (1,9)NOTO
C MPUTE THE SQUARE OF THE NORM OF THE VECTOR OF THE DEPENDENT VARIABLE,
C MPUTE THE MEAN OF THE DEPENDENT VARIABLE, YBAR.
1     FLNP=NP
      YY=Y(1)*Y(1)
      YBAR=Y(1)
      DO 2 I=2,NP
      YY=YY+Y(I)*Y(I)
2     YBAR=YBAR+Y(I)
C MPUTE THE MATRIX OF INNER PRODUCTS OF THE NORMALIZED FITTING FUNCTIONS
      YBAR=YBAR/FLNP
      IX=0
      JY=-1
      DO 8 J=1,NF
      IF (IX .NE. 0)THEN
      IX=IX-1
      JY=JY+1
      ELSE
      IX=JY+1
      JY=0
      END IF
      T=0.
      SUM=0.
      DO 4 I=1,NP
      GK=1.
      IF (IX .NE. 0) GK=X(I,1)**IX
      IF (JY .NE. 0) GK=GK*X(I,2)**JY
      Z(I)=GK
      T=T+GK*GK
4     SUM=SUM+Y(I)*GK
      GGSQT(J)=SQRT(T)
      YG(J)=SUM/GGSQT(J)
      GG(J,J)=1.0
      IF (J-1)8,8,5
5     KUL=J-1
      IXX=0
      JYY=-1
      DO 7 K=1,KUL
      IF (IXX .NE. 0)THEN
      IXX=IXX-1
      JYY=JYY+1
      ELSE
      IXX=JYY+1
      JYY=0
      END IF
      T=0.
      DO 6 I=1,NP
      GK=1.
      IF (IXX .NE. 0) GK=X(I,1)**IXX
      IF (JYY .NE. 0) GK=GK*X(I,2)**JYY
6     T=T+Z(I)*GK
      GG(J,K)=T/(GGSQT(J)*GGSQT(K))
7     GG(K,J)=GG(J,K)
8     CONTINUE
C MPUTE THE MATRIX OF COEFFICIENTS, Q, DEFINING THE ORTHOGONAL FUNCTIONS
C IN TERMS OF THE FITTING FUNCTIONS.
9     Q(1,1,NOTO)=1.
      S(1,1)=1.
      AA(1)=1.
      GO TO  (10,12)NOTO
10    DO 11 K=2,NF
11    AKJ(K,1)=-GG(K,1)
      GO TO 15
12    DO 14 K=2,NF
      SUM=0.
      DO 13 J=1,K
13    SUM=SUM+Q(K,J,1)*GG(J,1)
14     AKJ(K,1)=-SUM
15    DO 32 K=2,NF
      Q(K,K,NOTO)=1.
      S(K,K)=1.
      JUL=K-1
      DO 19 J=1,JUL
      GO TO (16,17)NOTO
16    T=AKJ(K,J)
      GO TO 19
17    T=0.
      DO 18 L=J,JUL
18    T=T+AKJ(K,L)*S(L,J)
19    S(K,J)=T
      DO 23 J=1,JUL
      SUM=0.
      DO 20 L=J,JUL
20    SUM=SUM+S(K,L)*Q(L,J,1)
      GO TO (21,22)NOTO
21    Q(K,J,1)=SUM
      GO TO 23
22    Q(K,J,2)=SUM+Q(K,J,1)
23    CONTINUE
      SUM=0.
      DO 25 J=1,K
      T=0.
      DO 24 L=1,K
C MPUTE THE VECTOR OF THE SQUARE OF THE NORM OF THE ORTHOGONAL FUNCTIONS
24    T=T+Q(K,L,NOTO)*GG(L,J)
25    SUM=SUM+Q(K,J,NOTO)*T
      AA(K)=SUM
      IF (K-NF)26,32,32
26    KPO=K+1
      DO 31 J=KPO,NF
      SUM=0.
      DO 30 L=1,K
      GO TO (27,28)NOTO
27    T=GG(J,L)
      GO TO 30
28    T=0.
      DO 29 M=1,J
29    T=T+Q(J,M,1)*GG(M,L)
30    SUM=SUM+Q(K,L,NOTO)*T
31    AKJ(J,K)=-SUM/AA(K)
32    CONTINUE
C MPUTE THE LEAST SQUARES COEFFICIENTS, A, FOR THE SOLUTION IN TERMS OF
C THE ORTHOGONAL FUNCTIONS.
      DO 34 K=1,NF
      SUM=0.
      DO 33 J=1,K
33    SUM=SUM+Q(K,J,NOTO)*YG(J)
34    A(K)=SUM/AA(K)
C MPUTE THE LEAST SQUARES COEFFICIENTS,D, FOR THE SOLUTION IN TERMS OF
C THE FITTING FUNCTIONS.
      DO 36 K=1,NF
      SUM=0.
      DO 35 J=K,NF
35    SUM=SUM+Q(J,K,NOTO)*A(J)
      D(K)=SUM/GGSQT(K)
36    DT(K)=SUM
C MPUTE THE STANDARD DEVIATION OF THE RESIDUALS, SDOR.
      SDOR=0.
      DO 38 I=1,NP
      XGGG=X(I,1)
      YGGG=X(I,2)
      SUM=POLY(XGGG,YGGG,D)
      T=Y(I)-SUM
38    SDOR=SDOR+T*T
      SDOR=SQRT(SDOR/(FLNP-NF))
      IF (IOOR)99,99,39
C MPUTE THE OPTIONAL OUTPUT ONLY IF (IOOR) IS POSITIVE.
39    DO 42 K=1,NF
C MPUTE THE CHECK FOR THE CONSISTENCY OF THE COEFFICIENTS D.
40    Z(K+200)=YG(K)
      SUM=0.
      DO 41 J=1,NF
41    SUM=SUM+DT(J)*GG(K,J)
      YGC(K)=SUM
      DYGC(K)=SUM-YG(K)
42    RYG(K)=DYGC(K)/YG(K)
C MPUTE THE ORTHONORMAL COEFFICIENTS, THE SUM OF THE SQUARES OF RESIDUAL
C THE ESTIMATES OF THE STANDARD DEVIATION OF THE RESIDUALS, AND THE
C TERM SIGNIFICANCE RATIO.
      SD(1)=A(1)
      CE(1)=YY-A(1)*A(1)*AA(1)
      DEN=NP-1
      SE(1)=SQRT(CE(1)/DEN)
      RDOE(1)=SD(1)/SE(1)
      DO 50 K=2,NF
      IF (AA(K)) 43,44,45
43    SD(K)=-SQRT(-AA(K))*A(K)
      GO TO 46
44    SD(K)=0.
      GO TO 46
45    SD(K)=SQRT(AA(K))*A(K)
46    CE(K)=CE(K-1)-A(K)*A(K)*AA(K)
      DEN=NP-K
      IF (CE(K))47,48,49
47    SE(K)=-SQRT(-CE(K)/DEN)
      GO TO 50
48    SE(K)=1.0E-33
      GO TO 50
49    SE(K)=SQRT(CE(K)/DEN)
50    RDOE(K)=SD(K)/SE(K)
C MPUTE THE ESTIMATE OF THE ERROR DUE TO ROUNDING AND THE RELATIVE ERROR
 
C IN THE LEAST SQUARES COEFFICIENTS,A.
      DO 60 K=1,NF
      KMO=K-1
      KPO=K+1
      T=0.
      IF (KMO)55,55,51
51    DO 54 J=1,KMO
      SUM=0.
      DO 53 L=1,J
      T1=0.
      DO 52 M=1,K
52    T1=T1+Q(K,M,NOTO)*GG(L,M)
53    SUM=SUM+Q(J,L,NOTO)*T1
54    T=T+A(J)*SUM
      IF(K-NF)55,59,59
55    DO 58 J=KPO,NF
      SUM=0.
      DO 57 L=1,J
      T1=0.
      DO 56 M=1,K
56    T1=T1+Q(K,M,NOTO)*GG(L,M)
57    SUM=SUM+Q(J,L,NOTO)*T1
58    T=T+A(J)*SUM
59    REE(K)=-T/AA(K)
60    RREE(K)=REE(K)/A(K)
 
99    CONTINUE
      RETURN
      END
