      SUBROUTINE PLOTIT(DAT,NSAMP,UNIT,ITWO)
C
      PARAMETER MAXCHAR=131, NPWIDE=786
      LOGICAL*1 XMASK(6),FIRST,LAST
      INTEGER UNIT
      LOGICAL*1 IOUT(MAXCHAR)
      DIMENSION DAT(NSAMP)
      DIMENSION IBIT(NPWIDE),DATA(NPWIDE)
      DATA XMASK/'01'X,'02'X,'04'X,'08'X,'10'X,'20'X/
      DATA FIRST,LAST/'05'X,'0A'X/
C
C ..IPIX IS THE NUMBER OF BITS PER PIXEL...
C
      IPIX=1
      ILENGTH=1
      ISTART=50
C
      DO 400 IROW=1,ILENGTH
C
        DO ISET=1,NPWIDE
          IBIT(ISET)=0
        END DO
        DO ISET = 1,MAXCHAR
          IOUT(ISET)='C0'X
        END DO
C
C ..THIS LOOP COUNTS THROUGH THE NUMBER OF ELEMENTS OF DAT...
C
        DO 300 ISAMP=1,NSAMP
C
C ..THIS LOOP COUNTS THROUGH THE NUMBER OF BITS IN EACH PIXEL...
C
          DO 200 IBITS=1,IPIX
C
C ..THE POSITION OF THE BIT UNDER CONSIDERATION IS CALCULATED...
C
            K=(ISAMP-1)*IPIX+IBITS+ISTART
C
            IF (DAT(ISAMP).GT.0.) IBIT(K)=1
C
  200     CONTINUE
  300   CONTINUE
C
C ..THE WORDS CONTAINING THE BITS TO WRITE TO THE TAPE...
C ..ARE THEN ASSEMBLED FROM THE BITS ALREADY FORMED...
C
      DO I=1,NPWIDE
        IF (IBIT(I) .EQ. 1)THEN
          KWORD=1+((I-1)/6)
          KBIT=1+MOD(I-1,6)
          IOUT(KWORD)=IOUT(KWORD).OR.XMASK(KBIT)
        END IF
      END DO
C
C ..THE LINE IS NOW WRITTEN TO THE FILE...
C
      WRITE(UNIT,99)FIRST,IOUT,LAST
99    FORMAT(133A1)
C
C     DUPLICATE THE LINE IF ITWO=2
C
      IF (ITWO .EQ. 2)THEN
        WRITE(UNIT,99)FIRST,IOUT,LAST
      END IF
  400 CONTINUE
C
      END
