      SUBROUTINE PROMPTI(PREFIX,NAME,IVALUE,ISTATUS)
      CHARACTER*(*) PREFIX,NAME
      CALL WRUSER(PREFIX,ISTAT)
      CALL CNPAR(NAME,ISTAT)
      CALL RDKEYI(NAME,.FALSE.,1,IVALUE,I,ISTATUS)
      END
