      SUBROUTINE PROMPTC(PREFIX,NAME,BUFFER,LENGTH,ISTATUS)
      CHARACTER*(*) PREFIX,BUFFER,NAME
      CALL WRUSER(PREFIX,ISTAT)
      CALL CNPAR(NAME,ISTAT)
      CALL RDKEYC(NAME,.FALSE.,1,BUFFER,I,ISTATUS)
      IF (ISTATUS .NE. 0)RETURN
      ISIZE=LEN(BUFFER)
      DO 10 I=ISIZE,1,-1
        LENGTH=I
        IF (BUFFER(I:I) .NE. ' ')GO TO 20
10    CONTINUE
20    RETURN
      END
C
