      SUBROUTINE SRFPR(IB2,JD1,NX,NY,X,Y)
C
C READS RECTANGULAR PIXEL ARRAY FROM THE ARGS. EACH PIXEL VALUE
C IS CONTAINED IN ONE INTEGER*2 ARRAY ELEMENT.
C 1ST SUBSCRIPT INCREASES WITH INCREASING X.
C 2ND SUBSCRIPT CORRESPONDS TO Y
C ARGUMENTS:
C    IB2   (EXIT) 2-D ARRAY CONTAINING PIXEL VALUES.
C    JD1   (ENTRY) 1ST DIMENSION OF ACTUAL ARRAY CORRESPDG TO IB2
C    NX,NY  (ENTRY) NUMBER OF PIXELS IN X- AND Y- DIRECTIONS
C    X,Y    (ENTRY) BOTTOM LEFT OF RECTANGLE
C
      PARAMETER BITS=16
      INTEGER JD1
      INTEGER*2 IB2(JD1,NY)
      INTEGER NX,NY, X,Y
      INTEGER PPE,HLINES
      INTEGER*2 CHECK
      REAL PPB
C   CHECK ARGUMENTS
      CHECK=IB2(1,1)
      CHECK=IB2(JD1,NY)
      CHECK=IB2(NX,NY)
C
C               NUMBER OF (P)IXELS (P)ER ARRAY (E)LEMENT
C               & PER (B)YTE (LATTER IS REAL BECAUSE IT COULD BE <1).
C
      PPE=16/BITS
      PPB=8.0/FLOAT(BITS)
      HLINES=10000
C
C     ADJUST HLINES TO THE SPACE ALLOWED BY ARGS_FPRI2
C
      HLINES=MIN(HLINES,(32767*PPE)/NX, (INT(32767.0*PPB)/NX))
C
C     CAN READ CHUNKS OF POSSIBLY MORE THAN 1 ROW.
C
      DO  JY=1,NY,HLINES
C       (NY2 IS # OF ROWS TO BE PUT THIS ITERATION)
        NY2=MIN(HLINES,NY-JY+1)
        CALL ARGS_FPRI2(IB2(1,JY),NY2*NX,X,Y+JY-1,
     1          NX,NY2)
      END DO
      END
C***********************************************************************
