      SUBROUTINE STAR(ARRAY,ICOL,IROW,TRIM,LLOG,VLO,VHI,
     1 IXPOS,IYPOS,IXOR,IYOR,ER,NDIMER,NCODE,CURSOR,FILE)
C
C ************************************************************
C
C     SUBROUTINE STAR(ARRAY,ICOL,IROW,TRIM,LLOG,VLO,VHI,
C                     IXPOS,IYPOS,IXOR,IYOR,ER,NDIMER,NCODE,
C                     CURSOR,FILE)
C
C     PACKAGE OF ROUTINES FOR FINDING AND REMOVING DEFECTS FROM
C     AN IMAGE ARRAY.  THE POSITION OF THE AREA TO DELETE MAY
C     BE SPECIFIED MANUALLY USING THE CURSOR, OF BY A SIMPLE
C     SEARCH ALGORITHM WHICH FINDS THE NEXT PIXEL ABOVE A
C     GIVEN THRESHOLD AND ALSO GREATER THAN ITS 8 NEIGHBOURING
C     PIXELS.  THE USER IS PROMPTED FOR THE DIAMETER OF A CIRCLE
C     OF PIXELS TO DELETE AROUND THIS POSITION, WHICH ARE
C     REPLACED BY AN INTERPOLATION OF A SURFACE FITTED TO
C     AN ANNULUS OF SURROUNDING PIXELS.  A CONSTANT, PLANAR,
C     QUADRATIC, OR CUBIC SURFACE MAY BE SPECIFIED (1,3,6, OR 10
C     TERMS).  THE INTERPOLATION IS DISPLAYED ON THE ARGS FOR
C     THE USER TO JUDGE THE QUALITY OF FIT.  IF NECESSARY, THE
C     ORIGINAL VALUES OF THE PIXELS MAY BE RESTORED AND A
C     DIFFERENT INTERPOLATION ATTEMPTED.
C
C     IRAY = 2 DIMENSIONAL IMAGE ARRAY (I*2)
C     ICOL = SIZE OF THE FIRST DIMENSION OF IRAY (I*4)
C     IROW = SIZE OF THE SECOND DIMENSION OF IRAY (I*4)
C
C     WRITTEN BY W D PENCE, UNIV. OF SUSSEX, OCT. 1980
C
C ****************************************************************
C
      REAL ARRAY(ICOL,IROW),ER(NDIMER)
	DIMENSION IRDATA(3)
	LOGICAL TRIM,LLOG,CURSOR,FILE
      CHARACTER BUFFER*80,INDCOL*1,CURCOL*1
C
	IRADIUS=20
	CURCOL='B'
	INDCOL='R'
	ITYPE=1
	NPOS=1
70	CONTINUE
	IF (CURSOR) THEN
		CALL ACURS(ITYPE,NPOS,IRADIUS,IXPOS,IYPOS,IRET,
     1  	           CURCOL,INDCOL,IRDATA)
		IF (IRET.EQ.0) GO TO 5
	NS=IRDATA(1)*2
	IXPOS=IRDATA(2)
	IYPOS=IRDATA(3)
	IS=IRDATA(2)-(IXOR)+1
	JS=IRDATA(3)-(IYOR)+1
	IRADIUS=IRDATA(1)
	ELSE
		READ (9,*,END=5) IS,JS,NS
	ENDIF
      CALL STRDELT(ARRAY,ICOL,IROW,IS,JS,TRIM,LLOG,VLO,VHI,
     1 NS,IXOR,IYOR,ER,NDIMER,NCODE,FILE,CURSOR)
      GO TO 70
5	CONTINUE
	END
