      SUBROUTINE STINIT
C
C     INITIALIZES THE RANDOM NUMBER COMMON BLOCK FOR THE STOCHASTIC
C       GREYSCALE ROUTINE FOR THE PRINTRONIX
C
      DOUBLE PRECISION X
      COMMON /LINKSTOCH/RAND(2000)
C
      CALL G05CBF(0)
C
C     G05CAF IS A NAG LIBRARY ROUTINE FOR PRODUCING RANDOM
C     NUMBERS IN THE RANGE 0.0 TO 1.0
C
      DO 100 I=1,2000
      X=G05CAF(X)
      RAND(I)=X
100   CONTINUE
      END
C*****************************************************************
