      SUBROUTINE STRCOPY(ARRAY,IROW,ICOL,TEMP,ISIZE,I1,I2,J1,J2)
C
C     STORE CURRENT STAR IMAGE IN TEMPORARY ARRAY
C
      REAL ARRAY(ICOL,IROW),TEMP(ISIZE)
C
      N=0
      DO 10 J=J1,J2
      DO 10 I=I1,I2
      N=N+1
10    TEMP(N)=ARRAY(I,J)
      RETURN
C
      ENTRY STRRSTR(ARRAY,IROW,ICOL,ITEMP,ISIZE,I1,I2,J1,J2)
C
C     RESTORE ARRAY TO PREVIOUS STATE
C
      N=0
      DO 20 J=J1,J2
      DO 20 I=I1,I2
      N=N+1
20    ARRAY(I,J)=TEMP(N)
      END
