      SUBROUTINE WINDOWQ(IWMIN,IWMAX,JWMIN,JWMAX,NCOL,NROW)
C
C     DEFINE WINDOW LIMITS
C
      CHARACTER ANS*1,BUFFER*80
C
1     WRITE(BUFFER,1001)
      CALL WRUSER(BUFFER,ISTATUS)
      WRITE(BUFFER,1002)IWMIN,IWMAX
      CALL WRUSER(BUFFER,ISTATUS)
      WRITE(BUFFER,1003)JWMIN,JWMAX
      CALL WRUSER(BUFFER,ISTATUS)
      CALL WRUSER('DO YOU WANT TO CHANGE THESE LIMITS? (Y/N)',
     1 ISTATUS)
      ANS='N'
      CALL RDKEYC('CHANGE',.TRUE.,1,ANS,NVAL,ISTATUS)
      IF (ANS(1:1) .EQ. 'N' .OR. ANS(1:1) .EQ. 'F')RETURN
      IF (ANS(1:1) .NE. 'Y' .AND. ANS(1:) .NE. 'T')GO TO 1
      GO TO 5
C
5     CALL WRUSER('MIN AND MAX COLS. (INCLUSIVE) OF WINDOW = ?'
     1 ,ISTATUS)
      WRITE(BUFFER,1005)NCOL
1005  FORMAT('   RANGE = 1 TO',I5)
      CALL PRMPT2I(BUFFER,'IVALUES',IWMIN,IWMAX,ISTATUS)
      IF (IWMAX .LT. IWMIN .OR.
     1 IWMIN .LT. 1 .OR. IWMAX .GT. NCOL)THEN
      CALL WRUSER('*** ERROR ***',ISTATUS)
      GO TO 5
      END IF
C
10    CALL WRUSER('MIN AND MAX ROWS (INCLUSIVE) OF WINDOW = ?'
     1 ,ISTATUS)
      WRITE(BUFFER,1005)NROW
      CALL PRMPT2I(BUFFER,'JVALUES',JWMIN,JWMAX,ISTATUS)
      IF (JWMAX .LT. JWMIN .OR.
     1 JWMIN .LT. 1 .OR. JWMAX .GT. NROW)THEN
      CALL WRUSER('***  ERROR ***',ISTATUS)
      GO TO 10
      END IF
C
1001  FORMAT('0WINDOW AREA IS SET TO:')
1002  FORMAT('    COLUMNS',I6,' TO',I6)
1003  FORMAT('       ROWS',I6,' TO',I6)
      END
C ***************************************************************
