      SUBROUTINE EXTLST(LIST,NITEM,LSTLEN,ITEM,IBYT1,IBYT2)
*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*PURPOSE
*	TO EXTRACT COLUMNS OF ENTRIES FROM A TABLE
*
*METHOD
*	COPY THE REQUIRED COLUMNS TO AN OUTPUT LIST
*
*ARGUMENTS
*	LIST (IN)
*	BYTE(4*NITEM,LSTLEN)
*		THE INPUT LIST
*	NITEM (IN)
*	INTEGER
*		THE NUMBER OF 4-BYTE ITEMS IN THE LIST
*	LSTLEN (IN)
*	INTEGER
*		THE NUMBER OF ENTRIES IN THE INPUT LIST
*	ITEM (OUT)
*	BYTE(IBYT2-IBYT1+1,LSTLEN)
*		AN ARRAY TO HOLD THE LIST OF COLUMNS EXTRACTED FROM
*		THE INPUT LIST
*	IBYT1,IBYT2 (IN)
*	INTEGER
*		THE STARTING AND ENDING BYTE COLUMNS TO BE EXTRACTED
*		FROM THE LIST
*
*CALLS
*	NONE
*
*NOTES
*	USES BYTE ARRAYS
*
*WRITTEN BY
*	R.F. WARREN-SMITH
*-----------------------------------------------------------------------
C
C
      BYTE LIST(4*NITEM,LSTLEN),ITEM(IBYT2-IBYT1+1,LSTLEN)
C
C COPY THE REQUITED REGION OF LIST INTO ITEM
C
      DO 2 J=1,LSTLEN
	DO 1 I=IBYT1,IBYT2
	  ITEM(I-IBYT1+1,J)=LIST(I,J)
    1   CONTINUE
    2 CONTINUE
      RETURN
      END
