      INTEGER FUNCTION IABORD(STR1,STR2,NBYT)
*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*PURPOSE
*	TO DETERMINE THE ALPHABETICAL ORDER OF 2 ASCII BYTE STRINGS
*
*METHOD
*	COMPARE EACH BYTE IN TURN, THE FIRST DIFFERENCE GIVES THE
*	ORDER
*
*ARGUMENTS
*	STR1,STR2 (IN)
*	BYTE(NBYT)
*		THE INPUT STRINGS
*	NBYT (IN)
*	INTEGER
*		LENGTH OF THE STRINGS
*	IABORD (FUNCTION NAME-OUT)
*	INTEGER
*		RETURNS 1 FOR AB ORDER, 0 FOR SAME AND -1 FOR REVERSE
*		ORDER
*
*CALLS
*	NONE
*
*NOTES
*	USES BYTE ARRAYS
*
*WRITTEN BY
*	R.F. WARREN-SMITH
*-----------------------------------------------------------------------
C
C
      BYTE STR1(NBYT),STR2(NBYT)
      IABORD=0
C
C SCAN THROUGH THE BYTES. THE FIRST NON-EQUAL PAIR DECIDES THE
C ALPHABETICAL ORDER. IF ALL EQUAL, IABORD REMAINS AT ZERO.
C
      DO 1 I=1,NBYT
        IF(STR1(I).LT.STR2(I)) THEN
	  IABORD=1
	  GO TO 2
	ELSE IF(STR1(I).GT.STR2(I)) THEN
	  IABORD=-1
	  GO TO 2
        ENDIF
    1 CONTINUE
    2 RETURN
      END
