      SUBROUTINE IMGSUM(IA,NPIX,NLINES,INVAL,SUM,NPT)
*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*PURPOSE
*	TO SUM ALL THE VALID PIXELS IN AN IMAGE
*
*METHOD
*	STRAIGHTFORWARD ADDITION
*
*ARGUMENTS
*	IA (IN)
*	INTEGER*2(NPIX,NLINES)
*		INPUT IMAGE
*	NPIX,NLINES (IN)
*	INTEGER
*		DIMENSIONS OF IMAGE
*	INVAL (IN)
*	INTEGER
*		INVALID PIXEL FLAG FOR IA
*	SUM (OUT)
*	REAL
*		SUM OF VALID PIXELS
*	NPT (OUT)
*	INTEGER
*		NUMBER OF VALID PIXELS USED
*
*CALLS
*	NONE
*
*NOTES
*	USES INTEGER*2 ARRAYS
*
*WRITTEN BY
*	R.F. WARREN-SMITH
*-----------------------------------------------------------------------
C
C
      INTEGER*2 IA(NPIX,NLINES)
C
C INITIALLISE SUM OF PIXELS AND VALID PIXEL COUNT
C
      SUM=0.0
      NPT=0
C
C SCAN IMAGE
C
      DO 2 J=1,NLINES
	DO 1 I=1,NPIX
C
C IF PIXEL IS VALID, ADD TO SUMS
C
	  IF(IA(I,J).NE.INVAL) THEN
	    SUM=SUM+IA(I,J)
	    NPT=NPT+1
	  ENDIF
    1	CONTINUE
    2 CONTINUE
      RETURN
      END
