      SUBROUTINE PTDSCR(FNAME,DNAME,TYPE,IVAL,RVAL,CVAL,IERR)
*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*PURPOSE
*	TO ADD INTEGER,REAL AND CHARACTER VALUES TO A DESCRIPTOR
*
*METHOD
*	CONVERT TO A CHARACTER STRING ACCORDING TO TYPE. ADD TO
*	DESCRIPTOR
*
*ARGUMENTS
*	FNAME (IN)
*	CHARACTER*(*)
*		THE PARAMETER NAME OF THE FRAME TO WHICH THE VALUE IS
*		ADDED
*	DNAME (IN)
*	CHARACTER*(*)
*		THE DESCRIPTOR ITEM NAME
*	TYPE (IN)
*	CHARACTER*(*)
*		ONE OF: 'REAL', 'INTEGER' OR 'CHARACTER'.. SPECIFIES
*		THE ITEM TYPE
*	IVAL (IN)
*	INTEGER
*		THE INTEGER ITEM, IF USED
*	RVAL (IN)
*	REAL
*		THE REAL ITEM, IF USED
*	CVAL (IN)
*	CHARACTER*(*)
*		THE CHARACTER ITEM, IF USED
*	IERR (OUT)
*	INTEGER
*		ERROR FLAG: ZERO FOR SUCCESS
*
*STARLINK PARAMETERS
*	THE FRAME SPECIFIED BY THE PARAMETER GIVEN IN 'FNAME' IS 
*	ACCESSED BY THIS ROUTINE
*
*CALLS
*	STARLINK:
*		RTOC,ITOC,WRDSCR
*
*WRITTEN BY
*	R.F. WARREN-SMITH
*-----------------------------------------------------------------------
C
C
      CHARACTER DSCPT(1)*30,FNAME*(*),DNAME*(*),TYPE*(*)
     +          ,CVAL*(*)
      IERR=0
C
C CONVERT INPUT VALUE TO A CHARACTER STRING, ACCORDING TO THE TYPE
C
      IF(TYPE.EQ.'CHARACTER') THEN
	DSCPT(1)=CVAL
      ELSE IF(TYPE.EQ.'REAL') THEN
	CALL RTOC(RVAL,DSCPT(1),IERR)
      ELSE IF(TYPE.EQ.'INTEGER') THEN
	CALL ITOC(IVAL,DSCPT(1),IERR)
      ENDIF
C
C IF SUCCESSFUL, ADD CHARACTERS TO DESCRIPTOR
C
      IF(IERR.EQ.0) THEN
	CALL WRDSCR(FNAME,DNAME,DSCPT,1,IERR)
      ENDIF
      RETURN
      END
