      SUBROUTINE XYLIST
*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*PURPOSE
*	TO PRINT THE CONTENTS OF AN X,Y LIST DATASET
*
*METHOD
*	OBTAIN INPUT DATASET. PRINT TITLE IF PRESENT. CALL PRLIST TO
*	PRINT THE DATA
*
*ARGUMENTS
*	NONE
*
*STARLINK PARAMETERS
*	INPUT
*		THE INPUT X,Y LIST DATASET
*
*CALLS
*	THIS PACKAGE:
*		GTXYLR,GTDSCR,PRLIST
*	STARLINK:
*		WRUSER,FRDATA
*
*NOTES
*	USES VAX %VAL FACILITY
*
*WRITTEN BY
*	R.F. WARREN-SMITH
*-----------------------------------------------------------------------
C
C
      CHARACTER CVAL*1,TITLE*30
C
C OBTAIN INPUT XY LIST
C
      CALL GTXYLR('INPUT',.FALSE.,NITEM,LSTLEN,IPIN,IERRXY)
      IF(IERRXY.EQ.0) THEN
C
C INPUT SUCCESSFULLY OBTAINED... EXTRACT TITLE
C
	TITLE=' '
	CALL GTDSCR('INPUT','TITLE','CHARACTER',IVAL,RVAL,TITLE,IERR)
C
C IF TITLE PRESENT, PRINT IT
C
	CALL WRUSER(' ',ISTAT)
	CALL WRUSER(' ',ISTAT)
	IF(TITLE.NE.' ') THEN
	  CALL WRUSER('                      TITLE: '//TITLE,ISTAT)
	  CALL WRUSER(' ',ISTAT)
	ENDIF
C
C CALL PRLIST TO PRINT THE CONTENTS OF THE LIST
C
	CALL PRLIST(%VAL(IPIN),NITEM,LSTLEN)
      ENDIF
C
C FREE DATA AREA AND RETURN
C
      CALL FRDATA(' ',ISTAT)
      RETURN
      END
