      program call_irasba
*
* PRODUCES AN IRAS IMAGE WHICH COVERS AN AREA OF THE SKY
* WHICH INCLUDES A SERIES OF INPUT IRAS IMAGES. THE IMAGE
* CONTAINS NO PIXEL DATA, JUST DESCRIPTORS.
*
      call irasba

      end
