      program call_irassh
*
* PERFORMS THE SAME FUNCTION AS EDRS:RESAMPLE, EXCEPT THAT
* IN ADDITION, IRASSHIFT UPDATES THE IRAS SPECIFIC DESCRIPTORS
* TO ACCOUNT FOR THE SHIFT PRODUCED BY RESAMPLE
*
      call irassh

      end
